//! Spain — the national days of Real Decreto 2001/1983 and the autonomous
//! communities' own, as the Dirección General de Trabajo publishes them.
//!
//! The regime is written up in `docs/systems/spain-holidays.md` in the
//! repository, with a worked example; this comment keeps the summary.
//!
//! Article 45 of Real Decreto 2001/1983 lists the fiestas laborales de
//! ámbito nacional. Some no community may replace; the rest — Epiphany,
//! Maundy Thursday, St Joseph's Day or St James's Day, and the Monday rest
//! of a national day that falls on a Sunday — each autonomous community
//! and the cities of Ceuta and Melilla may keep or replace with a day of
//! their own. Each tells the Ministry of Labour its choice for the next
//! year, and a resolution of the Dirección General de Trabajo (de Empleo
//! until 2017) publishes all nineteen lists in the BOE as a table. The
//! choice is a yearly act, not a rule.
//!
//! So the table carries two things:
//!
//! * **The nationwide days**, every one kept by all nineteen in every
//!   resolution read, as rules with no region: New Year's Day, Epiphany,
//!   Good Friday, Labour Day, the Assumption, the National Day, All
//!   Saints' Day, Constitution Day, the Immaculate Conception and
//!   Christmas Day, from 1990, the first whole year of the text of
//!   article 45 read, the years before a gap. Epiphany, which a community
//!   may replace, is nationwide only in the years whose resolution was
//!   read, and a gap in every other.
//! * **Each community's other days**, scoped to its ISO 3166-2 code, as
//!   the resolutions list them: its own day, the national days it chose to
//!   keep that it may replace (Maundy Thursday most of all), and the
//!   Monday rests it kept. They are [`Rule::Listed`] entries over a
//!   [`Listing`] per community, for the years whose resolution was read in
//!   the BOE's HTML text: 2013 to 2015 and 2018 to 2026. The resolutions
//!   for 2016 and 2017 publish their annex only as an image, so those
//!   years are a gap, and so is every year after 2026 and every year before
//!   2013, whose resolutions were not read. Every such day is a day off, [`Kind::Public`](crate::rule::Kind::Public):
//!   the resolutions list fiestas laborales, "retribuidas y no
//!   recuperables" (a community that has a thirteenth day makes one of
//!   them recuperable, which is still a day off).
//!
//! The names are the resolutions' Spanish ones, one spelling per day where
//! the resolutions vary it; the English names are this crate's. Not
//! carried: the islands' own days in the Canaries and the Aran Valley's,
//! which the resolutions note but which are not ISO 3166-2 subdivisions,
//! and the municipalities' two local days (article 46), which the
//! provincial and regional bulletins publish.

use crate::computus::offsets::GOOD_FRIDAY;
use crate::rule::{
    Days, HolidayRule, Listing, Rule, RuleSet, SATURDAY_SUNDAY, SourceDate, Subdivisions,
};

/// The resolutions read for 2013 to 2015.
const EARLY_RESOLUTIONS: &str = "Resoluciones de la Dirección General de Empleo de 30 de octubre \
     de 2012 (BOE-A-2012-13644), 8 de noviembre de 2013 (BOE-A-2013-12147) y 17 de octubre de \
     2014 (BOE-A-2014-10823), por las que se publica la relación de fiestas laborales para los \
     años 2013, 2014 y 2015, anexo";

/// The resolutions read for 2018 to 2026.
const LATE_RESOLUTIONS: &str = "Resoluciones de la Dirección General de Empleo de 9 de octubre de \
     2017 (BOE-A-2017-11639, corregida por BOE-A-2017-11952 y BOE-A-2017-12209) y de la \
     Dirección General de Trabajo de 16 de octubre de 2018 (BOE-A-2018-14369), 3 de octubre de \
     2019 (BOE-A-2019-14552), 28 de octubre de 2020 (BOE-A-2020-13343), 14 de octubre de 2021 \
     (BOE-A-2021-17113), 7 de octubre de 2022 (BOE-A-2022-16755), 23 de octubre de 2023 \
     (BOE-A-2023-22014), 15 de octubre de 2024 (BOE-A-2024-21316) y 17 de octubre de 2025 \
     (BOE-A-2025-21667), por las que se publica la relación de fiestas laborales para los años \
     2018 a 2026, anexo";

/// A community's day in the resolutions for 2013 to 2015, and a gap
/// before: the resolutions before 2013 were not read.
const fn early(
    name: &'static str,
    local_name: &'static str,
    days: &'static Listing,
    region: &'static [&'static str],
) -> HolidayRule {
    HolidayRule::fixed_public(
        name,
        local_name,
        Rule::listed(days.named(local_name), 2013, 2015),
    )
    .years(None, Some(2015))
    .in_regions(region)
    .cited(EARLY_RESOLUTIONS)
}

/// A community's day in the resolutions for 2018 to 2026, and a gap in
/// 2016 and 2017, whose annexes are images, and after 2026.
const fn late(
    name: &'static str,
    local_name: &'static str,
    days: &'static Listing,
    region: &'static [&'static str],
) -> HolidayRule {
    HolidayRule::fixed_public(
        name,
        local_name,
        Rule::listed(days.named(local_name), 2018, 2026),
    )
    .years(Some(2016), None)
    .in_regions(region)
    .cited(LATE_RESOLUTIONS)
}

/// The text of article 45 read, the version of Real Decreto 1346/1989, in
/// force from 8 November 1989: the first whole year it answers for. The
/// versions of 1983 and 1985 were not read.
const ARTICLE_45_READ: i32 = 1990;

/// Article 45 as read, cited by each nationwide day.
const ARTICLE_45: &str = "Real Decreto 2001/1983, art. 45.1, in the version of Real Decreto \
     1346/1989, en vigor a partir del 08/11/1989 (BOE-A-1983-20906, texto consolidado), \
     retrieved 2026-09-29; the versions of 1983 and of Real Decreto 2403/1985 not read";

/// Epiphany, 6 January, where a resolution read shows every community
/// keeping it — 2013 to 2015 and 2018 to 2026 — and else `None`: a day of
/// article 45.1 d), which a community may replace, is nationwide only in the
/// years whose resolution says it is.
fn epiphany_where_read(year: i64) -> Option<Days> {
    if !(2013..=2015).contains(&year) && !(2018..=2026).contains(&year) {
        return None;
    }
    Some(EPIPHANY.days_in_year(year))
}

/// 6 January.
static EPIPHANY: Rule = Rule::gregorian(1, 6);

/// A nationwide day of article 45, in the text read.
const fn national(name: &'static str, local_name: &'static str, rule: Rule) -> HolidayRule {
    HolidayRule::public(name, local_name, rule)
        .read_from(ARTICLE_45_READ)
        .cited(ARTICLE_45)
}

static RULES: &[HolidayRule] = &[
    // ── The nationwide days, article 45 ─────────────────────────────────
    national("New Year's Day", "Año Nuevo", Rule::gregorian(1, 1)),
    national(
        "Epiphany",
        "Epifanía del Señor",
        Rule::Unsettled(epiphany_where_read),
    )
    .cited(LATE_RESOLUTIONS),
    national("Good Friday", "Viernes Santo", Rule::easter(GOOD_FRIDAY)),
    national("Labour Day", "Fiesta del Trabajo", Rule::gregorian(5, 1)),
    national(
        "Assumption",
        "Asunción de la Virgen",
        Rule::gregorian(8, 15),
    ),
    national(
        "National Day",
        "Fiesta Nacional de España",
        Rule::gregorian(10, 12),
    ),
    national(
        "All Saints' Day",
        "Todos los Santos",
        Rule::gregorian(11, 1),
    ),
    national(
        "Constitution Day",
        "Día de la Constitución",
        Rule::gregorian(12, 6),
    ),
    national(
        "Immaculate Conception",
        "Inmaculada Concepción",
        Rule::gregorian(12, 8),
    ),
    national(
        "Christmas Day",
        "Natividad del Señor",
        Rule::gregorian(12, 25),
    ),
    // ── The communities' days, as the resolutions list them ─────────────
    // Andalusia
    early(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Day of Andalusia",
        "Día de Andalucía",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Day of Andalusia",
        "Día de Andalucía",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Maundy Thursday",
        "Jueves Santo",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Maundy Thursday",
        "Jueves Santo",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &ANDALUSIA_DAYS,
        ANDALUSIA,
    ),
    // Aragon
    early(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early("Maundy Thursday", "Jueves Santo", &ARAGON_DAYS, ARAGON),
    late("Maundy Thursday", "Jueves Santo", &ARAGON_DAYS, ARAGON),
    early(
        "St George's Day, Day of Aragon",
        "San Jorge/Día de Aragón",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "St George's Day, Day of Aragon",
        "San Jorge/Día de Aragón",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after St George's Day",
        "Lunes siguiente a San Jorge/Día de Aragón",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after St George's Day",
        "Lunes siguiente a San Jorge/Día de Aragón",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &ARAGON_DAYS,
        ARAGON,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &ARAGON_DAYS,
        ARAGON,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &ARAGON_DAYS,
        ARAGON,
    ),
    // Asturias
    early(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early("Maundy Thursday", "Jueves Santo", &ASTURIAS_DAYS, ASTURIAS),
    late("Maundy Thursday", "Jueves Santo", &ASTURIAS_DAYS, ASTURIAS),
    early(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Day of Asturias",
        "Día de Asturias",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Day of Asturias",
        "Día de Asturias",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Monday after the Day of Asturias",
        "Lunes siguiente al Día de Asturias",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after the Day of Asturias",
        "Lunes siguiente al Día de Asturias",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &ASTURIAS_DAYS,
        ASTURIAS,
    ),
    // the Balearic Islands
    early(
        "Day of the Balearic Islands",
        "Día de les Illes Balears",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    late(
        "Day of the Balearic Islands",
        "Día de les Illes Balears",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    early(
        "Monday after the Day of the Balearic Islands",
        "Lunes siguiente al Día de les Illes Balears",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    late(
        "Monday after the Day of the Balearic Islands",
        "Lunes siguiente al Día de les Illes Balears",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    early(
        "Maundy Thursday",
        "Jueves Santo",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    late(
        "Maundy Thursday",
        "Jueves Santo",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    early(
        "Easter Monday",
        "Lunes de Pascua",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    late(
        "Easter Monday",
        "Lunes de Pascua",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    early(
        "St Stephen's Day",
        "San Esteban",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    late(
        "St Stephen's Day",
        "San Esteban",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &BALEARIC_ISLANDS_DAYS,
        BALEARIC_ISLANDS,
    ),
    // the Basque Country
    early(
        "St Joseph's Day",
        "San José",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    late(
        "St Joseph's Day",
        "San José",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    early(
        "Maundy Thursday",
        "Jueves Santo",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    late(
        "Maundy Thursday",
        "Jueves Santo",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    early(
        "Easter Monday",
        "Lunes de Pascua",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    late(
        "Easter Monday",
        "Lunes de Pascua",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    early(
        "St James's Day",
        "Santiago Apóstol",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    late(
        "St James's Day",
        "Santiago Apóstol",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    early(
        "Fifth Centenary of the First Circumnavigation",
        "V Centenario Vuelta al Mundo",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    late(
        "Fifth Centenary of the First Circumnavigation",
        "V Centenario Vuelta al Mundo",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    early(
        "Day of the Basque Country",
        "Día del País Vasco-Euskadiko Eguna",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    late(
        "Day of the Basque Country",
        "Día del País Vasco-Euskadiko Eguna",
        &BASQUE_COUNTRY_DAYS,
        BASQUE_COUNTRY,
    ),
    // the Canary Islands
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    early(
        "Maundy Thursday",
        "Jueves Santo",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    late(
        "Maundy Thursday",
        "Jueves Santo",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    early(
        "Day of the Canary Islands",
        "Día de Canarias",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    late(
        "Day of the Canary Islands",
        "Día de Canarias",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    early(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    late(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &CANARY_ISLANDS_DAYS,
        CANARY_ISLANDS,
    ),
    // Cantabria
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "Maundy Thursday",
        "Jueves Santo",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Maundy Thursday",
        "Jueves Santo",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "Easter Monday",
        "Lunes de Pascua",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Easter Monday",
        "Lunes de Pascua",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "St James's Day",
        "Santiago Apóstol",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "St James's Day",
        "Santiago Apóstol",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "Day of the Institutions of Cantabria",
        "Día de las Instituciones de Cantabria",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Day of the Institutions of Cantabria",
        "Día de las Instituciones de Cantabria",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "Our Lady of Bien Aparecida",
        "La Bien Aparecida",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Our Lady of Bien Aparecida",
        "La Bien Aparecida",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &CANTABRIA_DAYS,
        CANTABRIA,
    ),
    // Castile and León
    early(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Maundy Thursday",
        "Jueves Santo",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Maundy Thursday",
        "Jueves Santo",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Day of Castile and León",
        "Fiesta de Castilla y León",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Day of Castile and León",
        "Fiesta de Castilla y León",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "St James's Day",
        "Santiago Apóstol",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "St James's Day",
        "Santiago Apóstol",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after the Assumption",
        "Lunes siguiente a la Asunción de la Virgen",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &CASTILE_AND_LEON_DAYS,
        CASTILE_AND_LEON,
    ),
    // Castilla-La Mancha
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    early(
        "St Joseph's Day",
        "San José",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "St Joseph's Day",
        "San José",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    early(
        "Maundy Thursday",
        "Jueves Santo",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "Maundy Thursday",
        "Jueves Santo",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    early(
        "Easter Monday",
        "Lunes de Pascua",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "Easter Monday",
        "Lunes de Pascua",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    early(
        "Corpus Christi",
        "Corpus Christi",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "Corpus Christi",
        "Corpus Christi",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    early(
        "Day of Castilla-La Mancha",
        "Día de Castilla-La Mancha",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "Day of Castilla-La Mancha",
        "Día de Castilla-La Mancha",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &CASTILLA_LA_MANCHA_DAYS,
        CASTILLA_LA_MANCHA,
    ),
    // Catalonia
    early(
        "Easter Monday",
        "Lunes de Pascua",
        &CATALONIA_DAYS,
        CATALONIA,
    ),
    late(
        "Easter Monday",
        "Lunes de Pascua",
        &CATALONIA_DAYS,
        CATALONIA,
    ),
    early(
        "Whit Monday",
        "Lunes de Pascua Granada",
        &CATALONIA_DAYS,
        CATALONIA,
    ),
    late(
        "Whit Monday",
        "Lunes de Pascua Granada",
        &CATALONIA_DAYS,
        CATALONIA,
    ),
    early("St John's Day", "San Juan", &CATALONIA_DAYS, CATALONIA),
    late("St John's Day", "San Juan", &CATALONIA_DAYS, CATALONIA),
    early(
        "National Day of Catalonia",
        "Fiesta Nacional de Cataluña",
        &CATALONIA_DAYS,
        CATALONIA,
    ),
    late(
        "National Day of Catalonia",
        "Fiesta Nacional de Cataluña",
        &CATALONIA_DAYS,
        CATALONIA,
    ),
    early(
        "St Stephen's Day",
        "San Esteban",
        &CATALONIA_DAYS,
        CATALONIA,
    ),
    late(
        "St Stephen's Day",
        "San Esteban",
        &CATALONIA_DAYS,
        CATALONIA,
    ),
    // Ceuta
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CEUTA_DAYS,
        CEUTA,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &CEUTA_DAYS,
        CEUTA,
    ),
    early("Maundy Thursday", "Jueves Santo", &CEUTA_DAYS, CEUTA),
    late("Maundy Thursday", "Jueves Santo", &CEUTA_DAYS, CEUTA),
    early(
        "Eid al-Adha",
        "Fiesta del Sacrificio-Eidul Adha",
        &CEUTA_DAYS,
        CEUTA,
    ),
    late(
        "Eid al-Adha",
        "Fiesta del Sacrificio-Eidul Adha",
        &CEUTA_DAYS,
        CEUTA,
    ),
    early(
        "Our Lady of Africa",
        "Nuestra Señora de África",
        &CEUTA_DAYS,
        CEUTA,
    ),
    late(
        "Our Lady of Africa",
        "Nuestra Señora de África",
        &CEUTA_DAYS,
        CEUTA,
    ),
    early("Day of Ceuta", "Día de Ceuta", &CEUTA_DAYS, CEUTA),
    late("Day of Ceuta", "Día de Ceuta", &CEUTA_DAYS, CEUTA),
    early(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &CEUTA_DAYS,
        CEUTA,
    ),
    late(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &CEUTA_DAYS,
        CEUTA,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &CEUTA_DAYS,
        CEUTA,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &CEUTA_DAYS,
        CEUTA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CEUTA_DAYS,
        CEUTA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &CEUTA_DAYS,
        CEUTA,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &CEUTA_DAYS,
        CEUTA,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &CEUTA_DAYS,
        CEUTA,
    ),
    // the Community of Madrid
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &MADRID_DAYS,
        MADRID,
    ),
    early(
        "St Joseph's Day, moved",
        "Traslado de San José",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "St Joseph's Day, moved",
        "Traslado de San José",
        &MADRID_DAYS,
        MADRID,
    ),
    early("St Joseph's Day", "San José", &MADRID_DAYS, MADRID),
    late("St Joseph's Day", "San José", &MADRID_DAYS, MADRID),
    early(
        "Monday after St Joseph's Day",
        "Lunes siguiente a San José",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Monday after St Joseph's Day",
        "Lunes siguiente a San José",
        &MADRID_DAYS,
        MADRID,
    ),
    early("Maundy Thursday", "Jueves Santo", &MADRID_DAYS, MADRID),
    late("Maundy Thursday", "Jueves Santo", &MADRID_DAYS, MADRID),
    early(
        "Day of the Community of Madrid",
        "Fiesta de la Comunidad de Madrid",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Day of the Community of Madrid",
        "Fiesta de la Comunidad de Madrid",
        &MADRID_DAYS,
        MADRID,
    ),
    early(
        "Monday after the Day of the Community of Madrid",
        "Lunes siguiente al Día de la Comunidad de Madrid",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Monday after the Day of the Community of Madrid",
        "Lunes siguiente al Día de la Comunidad de Madrid",
        &MADRID_DAYS,
        MADRID,
    ),
    early("Corpus Christi", "Corpus Christi", &MADRID_DAYS, MADRID),
    late("Corpus Christi", "Corpus Christi", &MADRID_DAYS, MADRID),
    early("St James's Day", "Santiago Apóstol", &MADRID_DAYS, MADRID),
    late("St James's Day", "Santiago Apóstol", &MADRID_DAYS, MADRID),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &MADRID_DAYS,
        MADRID,
    ),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &MADRID_DAYS,
        MADRID,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &MADRID_DAYS,
        MADRID,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &MADRID_DAYS,
        MADRID,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &MADRID_DAYS,
        MADRID,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &MADRID_DAYS,
        MADRID,
    ),
    // Extremadura
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Shrove Tuesday",
        "Martes de Carnaval",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Shrove Tuesday",
        "Martes de Carnaval",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "St Joseph's Day",
        "San José",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "St Joseph's Day",
        "San José",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Maundy Thursday",
        "Jueves Santo",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Maundy Thursday",
        "Jueves Santo",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Day of Extremadura",
        "Día de Extremadura",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Day of Extremadura",
        "Día de Extremadura",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Monday after the Day of Extremadura",
        "Lunes siguiente al Día de Extremadura",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Monday after the Day of Extremadura",
        "Lunes siguiente al Día de Extremadura",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Monday after the National Day of Spain",
        "Lunes siguiente a la Fiesta Nacional de España",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &EXTREMADURA_DAYS,
        EXTREMADURA,
    ),
    // Galicia
    early("St Joseph's Day", "San José", &GALICIA_DAYS, GALICIA),
    late("St Joseph's Day", "San José", &GALICIA_DAYS, GALICIA),
    early(
        "Day after St Joseph's Day",
        "Día siguiente a San José",
        &GALICIA_DAYS,
        GALICIA,
    ),
    late(
        "Day after St Joseph's Day",
        "Día siguiente a San José",
        &GALICIA_DAYS,
        GALICIA,
    ),
    early("Maundy Thursday", "Jueves Santo", &GALICIA_DAYS, GALICIA),
    late("Maundy Thursday", "Jueves Santo", &GALICIA_DAYS, GALICIA),
    early(
        "Galician Literature Day",
        "Día de las Letras Gallegas",
        &GALICIA_DAYS,
        GALICIA,
    ),
    late(
        "Galician Literature Day",
        "Día de las Letras Gallegas",
        &GALICIA_DAYS,
        GALICIA,
    ),
    early("St John's Day", "San Juan", &GALICIA_DAYS, GALICIA),
    late("St John's Day", "San Juan", &GALICIA_DAYS, GALICIA),
    early(
        "St James's Day, National Day of Galicia",
        "Santiago Apóstol/Día Nacional de Galicia",
        &GALICIA_DAYS,
        GALICIA,
    ),
    late(
        "St James's Day, National Day of Galicia",
        "Santiago Apóstol/Día Nacional de Galicia",
        &GALICIA_DAYS,
        GALICIA,
    ),
    early(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &GALICIA_DAYS,
        GALICIA,
    ),
    late(
        "Monday after All Saints' Day",
        "Lunes siguiente a Todos los Santos",
        &GALICIA_DAYS,
        GALICIA,
    ),
    // La Rioja
    early("Maundy Thursday", "Jueves Santo", &LA_RIOJA_DAYS, LA_RIOJA),
    late("Maundy Thursday", "Jueves Santo", &LA_RIOJA_DAYS, LA_RIOJA),
    early("Easter Monday", "Lunes de Pascua", &LA_RIOJA_DAYS, LA_RIOJA),
    late("Easter Monday", "Lunes de Pascua", &LA_RIOJA_DAYS, LA_RIOJA),
    early(
        "Day of La Rioja",
        "Día de La Rioja",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    late(
        "Day of La Rioja",
        "Día de La Rioja",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    early(
        "Monday after the Day of La Rioja",
        "Lunes siguiente al Día de La Rioja",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    late(
        "Monday after the Day of La Rioja",
        "Lunes siguiente al Día de La Rioja",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &LA_RIOJA_DAYS,
        LA_RIOJA,
    ),
    // Melilla
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &MELILLA_DAYS,
        MELILLA,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &MELILLA_DAYS,
        MELILLA,
    ),
    early(
        "Statute of Autonomy of Melilla Day",
        "Estatuto de Autonomía de la Ciudad de Melilla",
        &MELILLA_DAYS,
        MELILLA,
    ),
    late(
        "Statute of Autonomy of Melilla Day",
        "Estatuto de Autonomía de la Ciudad de Melilla",
        &MELILLA_DAYS,
        MELILLA,
    ),
    early("St Joseph's Day", "San José", &MELILLA_DAYS, MELILLA),
    late("St Joseph's Day", "San José", &MELILLA_DAYS, MELILLA),
    early("Eid al-Fitr", "Fiesta del Eid Fitr", &MELILLA_DAYS, MELILLA),
    late("Eid al-Fitr", "Fiesta del Eid Fitr", &MELILLA_DAYS, MELILLA),
    early("Maundy Thursday", "Jueves Santo", &MELILLA_DAYS, MELILLA),
    late("Maundy Thursday", "Jueves Santo", &MELILLA_DAYS, MELILLA),
    early(
        "Eid al-Adha",
        "Fiesta del Sacrificio-Aid Al Adha",
        &MELILLA_DAYS,
        MELILLA,
    ),
    late(
        "Eid al-Adha",
        "Fiesta del Sacrificio-Aid Al Adha",
        &MELILLA_DAYS,
        MELILLA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &MELILLA_DAYS,
        MELILLA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &MELILLA_DAYS,
        MELILLA,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &MELILLA_DAYS,
        MELILLA,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &MELILLA_DAYS,
        MELILLA,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &MELILLA_DAYS,
        MELILLA,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &MELILLA_DAYS,
        MELILLA,
    ),
    // Navarre
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &NAVARRE_DAYS,
        NAVARRE,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &NAVARRE_DAYS,
        NAVARRE,
    ),
    early("St Joseph's Day", "San José", &NAVARRE_DAYS, NAVARRE),
    late("St Joseph's Day", "San José", &NAVARRE_DAYS, NAVARRE),
    early("Maundy Thursday", "Jueves Santo", &NAVARRE_DAYS, NAVARRE),
    late("Maundy Thursday", "Jueves Santo", &NAVARRE_DAYS, NAVARRE),
    early("Easter Monday", "Lunes de Pascua", &NAVARRE_DAYS, NAVARRE),
    late("Easter Monday", "Lunes de Pascua", &NAVARRE_DAYS, NAVARRE),
    early("St James's Day", "Santiago Apóstol", &NAVARRE_DAYS, NAVARRE),
    late("St James's Day", "Santiago Apóstol", &NAVARRE_DAYS, NAVARRE),
    early(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &NAVARRE_DAYS,
        NAVARRE,
    ),
    late(
        "Day after All Saints' Day",
        "Día siguiente a Todos los Santos",
        &NAVARRE_DAYS,
        NAVARRE,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &NAVARRE_DAYS,
        NAVARRE,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &NAVARRE_DAYS,
        NAVARRE,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &NAVARRE_DAYS,
        NAVARRE,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &NAVARRE_DAYS,
        NAVARRE,
    ),
    // the Region of Murcia
    early(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &MURCIA_DAYS,
        MURCIA,
    ),
    late(
        "Monday after New Year's Day",
        "Lunes siguiente a Año Nuevo",
        &MURCIA_DAYS,
        MURCIA,
    ),
    early(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &MURCIA_DAYS,
        MURCIA,
    ),
    late(
        "Monday after Epiphany",
        "Lunes siguiente a la Epifanía del Señor",
        &MURCIA_DAYS,
        MURCIA,
    ),
    early("St Joseph's Day", "San José", &MURCIA_DAYS, MURCIA),
    late("St Joseph's Day", "San José", &MURCIA_DAYS, MURCIA),
    early("Maundy Thursday", "Jueves Santo", &MURCIA_DAYS, MURCIA),
    late("Maundy Thursday", "Jueves Santo", &MURCIA_DAYS, MURCIA),
    early(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &MURCIA_DAYS,
        MURCIA,
    ),
    late(
        "Monday after Labour Day",
        "Lunes siguiente a la Fiesta del Trabajo",
        &MURCIA_DAYS,
        MURCIA,
    ),
    early(
        "Day of the Region of Murcia",
        "Día de la Región de Murcia",
        &MURCIA_DAYS,
        MURCIA,
    ),
    late(
        "Day of the Region of Murcia",
        "Día de la Región de Murcia",
        &MURCIA_DAYS,
        MURCIA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &MURCIA_DAYS,
        MURCIA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &MURCIA_DAYS,
        MURCIA,
    ),
    early(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &MURCIA_DAYS,
        MURCIA,
    ),
    late(
        "Monday after the Immaculate Conception",
        "Lunes siguiente a la Inmaculada Concepción",
        &MURCIA_DAYS,
        MURCIA,
    ),
    early(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &MURCIA_DAYS,
        MURCIA,
    ),
    late(
        "Monday after Christmas Day",
        "Lunes siguiente a la Natividad del Señor",
        &MURCIA_DAYS,
        MURCIA,
    ),
    // the Valencian Community
    early("Fallas Monday", "Lunes de Fallas", &VALENCIA_DAYS, VALENCIA),
    late("Fallas Monday", "Lunes de Fallas", &VALENCIA_DAYS, VALENCIA),
    early("St Joseph's Day", "San José", &VALENCIA_DAYS, VALENCIA),
    late("St Joseph's Day", "San José", &VALENCIA_DAYS, VALENCIA),
    early("Easter Monday", "Lunes de Pascua", &VALENCIA_DAYS, VALENCIA),
    late("Easter Monday", "Lunes de Pascua", &VALENCIA_DAYS, VALENCIA),
    early("Maundy Thursday", "Jueves Santo", &VALENCIA_DAYS, VALENCIA),
    late("Maundy Thursday", "Jueves Santo", &VALENCIA_DAYS, VALENCIA),
    early("St John's Day", "San Juan", &VALENCIA_DAYS, VALENCIA),
    late("St John's Day", "San Juan", &VALENCIA_DAYS, VALENCIA),
    early(
        "Day of the Valencian Community",
        "Día de la Comunitat Valenciana",
        &VALENCIA_DAYS,
        VALENCIA,
    ),
    late(
        "Day of the Valencian Community",
        "Día de la Comunitat Valenciana",
        &VALENCIA_DAYS,
        VALENCIA,
    ),
    early(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &VALENCIA_DAYS,
        VALENCIA,
    ),
    late(
        "Monday after Constitution Day",
        "Lunes siguiente al Día de la Constitución Española",
        &VALENCIA_DAYS,
        VALENCIA,
    ),
];

/// Spain.
pub static SPAIN: RuleSet = RuleSet {
    code: "ES",
    english_name: "Spain",
    rules: RULES,
    substitution: &[],
    bridges: &[],
    includes: &[],
    weekend: SATURDAY_SUNDAY,
    sources_checked: SourceDate::new(2026, 9, 29),
    sources: "Real Decreto 2001/1983, de 28 de julio, arts. 45 and 46, as amended by Real Decreto \
              2403/1985 and Real Decreto 1346/1989, on the BOE \
              (boe.es/buscar/act.php?id=BOE-A-1983-20906), retrieved 2026-09-26 and 2026-09-29; \
              the Resoluciones de la Dirección General de Empleo and de Trabajo publishing the \
              fiestas laborales of 2013 to 2015 and 2018 to 2026, with the two corrections of \
              the 2018 one, in the BOE's HTML text (boe.es/diario_boe/txt.php), retrieved \
              2026-09-29, each cited on its entries; the resolutions for 2016 (BOE-A-2015-11348) \
              and 2017 (BOE-A-2016-9244), whose annexes are images, not read; the Estatuto de \
              los Trabajadores (Real Decreto Legislativo 2/2015), art. 37.2, as the resolutions \
              quote it, not read. The communities' days are the resolutions' and every other \
              year is a gap; the municipalities' local days are not carried",
    subdivisions: Subdivisions::Read(&[]),
};

const ANDALUSIA: &[&str] = &["ES-AN"];
const ARAGON: &[&str] = &["ES-AR"];
const ASTURIAS: &[&str] = &["ES-AS"];
const BALEARIC_ISLANDS: &[&str] = &["ES-IB"];
const BASQUE_COUNTRY: &[&str] = &["ES-PV"];
const CANARY_ISLANDS: &[&str] = &["ES-CN"];
const CANTABRIA: &[&str] = &["ES-CB"];
const CASTILE_AND_LEON: &[&str] = &["ES-CL"];
const CASTILLA_LA_MANCHA: &[&str] = &["ES-CM"];
const CATALONIA: &[&str] = &["ES-CT"];
const CEUTA: &[&str] = &["ES-CE"];
const MADRID: &[&str] = &["ES-MD"];
const EXTREMADURA: &[&str] = &["ES-EX"];
const GALICIA: &[&str] = &["ES-GA"];
const LA_RIOJA: &[&str] = &["ES-RI"];
const MELILLA: &[&str] = &["ES-ML"];
const NAVARRE: &[&str] = &["ES-NC"];
const MURCIA: &[&str] = &["ES-MC"];
const VALENCIA: &[&str] = &["ES-VC"];

/// The days of Andalusia (ES-AN) in the resolutions read.
static ANDALUSIA_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 2, 28, "Día de Andalucía"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2014, 2, 28, "Día de Andalucía"),
    (2014, 4, 17, "Jueves Santo"),
    (
        2014,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2015, 2, 28, "Día de Andalucía"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 2, 28, "Día de Andalucía"),
    (2018, 3, 29, "Jueves Santo"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 2, 28, "Día de Andalucía"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 2, 28, "Día de Andalucía"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 3, 1, "Día de Andalucía"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 8, 16, "Lunes siguiente a la Asunción de la Virgen"),
    (2022, 2, 28, "Día de Andalucía"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 2, "Lunes siguiente a la Fiesta del Trabajo"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 1, 2, "Lunes siguiente a Año Nuevo"),
    (2023, 2, 28, "Día de Andalucía"),
    (2023, 4, 6, "Jueves Santo"),
    (2024, 2, 28, "Día de Andalucía"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2025, 2, 28, "Día de Andalucía"),
    (2025, 4, 17, "Jueves Santo"),
    (
        2025,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2026, 2, 28, "Día de Andalucía"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of Aragon (ES-AR) in the resolutions read.
static ARAGON_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 4, 23, "San Jorge/Día de Aragón"),
    (2013, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 4, 23, "San Jorge/Día de Aragón"),
    (
        2014,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 4, 23, "San Jorge/Día de Aragón"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 4, 23, "San Jorge/Día de Aragón"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 4, 23, "San Jorge/Día de Aragón"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 4, 23, "San Jorge/Día de Aragón"),
    (2020, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 4, 23, "San Jorge/Día de Aragón"),
    (2021, 8, 16, "Lunes siguiente a la Asunción de la Virgen"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 4, 23, "San Jorge/Día de Aragón"),
    (2022, 5, 2, "Lunes siguiente a la Fiesta del Trabajo"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 1, 2, "Lunes siguiente a Año Nuevo"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 4, 24, "Lunes siguiente a San Jorge/Día de Aragón"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 4, 23, "San Jorge/Día de Aragón"),
    (2024, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 4, 23, "San Jorge/Día de Aragón"),
    (
        2025,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 4, 23, "San Jorge/Día de Aragón"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of Asturias (ES-AS) in the resolutions read.
static ASTURIAS_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 9, 9, "Lunes siguiente al Día de Asturias"),
    (2013, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 9, 8, "Día de Asturias"),
    (
        2014,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 9, 8, "Día de Asturias"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 9, 8, "Día de Asturias"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 9, 9, "Lunes siguiente al Día de Asturias"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 9, 8, "Día de Asturias"),
    (2020, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 8, 16, "Lunes siguiente a la Asunción de la Virgen"),
    (2021, 9, 8, "Día de Asturias"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 2, "Lunes siguiente a la Fiesta del Trabajo"),
    (2022, 9, 8, "Día de Asturias"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 1, 2, "Lunes siguiente a Año Nuevo"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 9, 8, "Día de Asturias"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 9, 9, "Lunes siguiente al Día de Asturias"),
    (2024, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 9, 8, "Día de Asturias"),
    (
        2025,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 9, 8, "Día de Asturias"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of the Balearic Islands (ES-IB) in the resolutions read.
static BALEARIC_ISLANDS_DAYS: Listing = Listing::Named(&[
    (2013, 3, 1, "Día de les Illes Balears"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 4, 1, "Lunes de Pascua"),
    (2013, 12, 26, "San Esteban"),
    (2014, 3, 1, "Día de les Illes Balears"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 12, 26, "San Esteban"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 4, 6, "Lunes de Pascua"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 1, "Día de les Illes Balears"),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 4, 2, "Lunes de Pascua"),
    (2019, 3, 1, "Día de les Illes Balears"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 4, 22, "Lunes de Pascua"),
    (2019, 12, 26, "San Esteban"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 4, 13, "Lunes de Pascua"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2020, 12, 26, "San Esteban"),
    (2021, 3, 1, "Día de les Illes Balears"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 4, 5, "Lunes de Pascua"),
    (2022, 3, 1, "Día de les Illes Balears"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 4, 18, "Lunes de Pascua"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 3, 1, "Día de les Illes Balears"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 4, 10, "Lunes de Pascua"),
    (2024, 3, 1, "Día de les Illes Balears"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 4, 1, "Lunes de Pascua"),
    (2025, 3, 1, "Día de les Illes Balears"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 12, 26, "San Esteban"),
    (2026, 3, 2, "Lunes siguiente al Día de les Illes Balears"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 4, 6, "Lunes de Pascua"),
    (2026, 12, 26, "San Esteban"),
]);

/// The days of the Basque Country (ES-PV) in the resolutions read.
static BASQUE_COUNTRY_DAYS: Listing = Listing::Named(&[
    (2013, 3, 28, "Jueves Santo"),
    (2013, 4, 1, "Lunes de Pascua"),
    (2013, 7, 25, "Santiago Apóstol"),
    (2013, 10, 25, "Día del País Vasco-Euskadiko Eguna"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 4, 21, "Lunes de Pascua"),
    (2014, 10, 25, "Día del País Vasco-Euskadiko Eguna"),
    (2015, 3, 19, "San José"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 4, 6, "Lunes de Pascua"),
    (2015, 7, 25, "Santiago Apóstol"),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 4, 2, "Lunes de Pascua"),
    (2019, 3, 19, "San José"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 4, 22, "Lunes de Pascua"),
    (2019, 7, 25, "Santiago Apóstol"),
    (2020, 3, 19, "San José"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 4, 13, "Lunes de Pascua"),
    (2020, 7, 25, "Santiago Apóstol"),
    (2021, 3, 19, "San José"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 4, 5, "Lunes de Pascua"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 4, 18, "Lunes de Pascua"),
    (2022, 7, 25, "Santiago Apóstol"),
    (2022, 9, 6, "V Centenario Vuelta al Mundo"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 4, 10, "Lunes de Pascua"),
    (2023, 7, 25, "Santiago Apóstol"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 4, 1, "Lunes de Pascua"),
    (2024, 7, 25, "Santiago Apóstol"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 4, 21, "Lunes de Pascua"),
    (2025, 7, 25, "Santiago Apóstol"),
    (2026, 3, 19, "San José"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 4, 6, "Lunes de Pascua"),
    (2026, 7, 25, "Santiago Apóstol"),
]);

/// The days of the Canary Islands (ES-CN) in the resolutions read.
static CANARY_ISLANDS_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 5, 30, "Día de Canarias"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 5, 30, "Día de Canarias"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 5, 30, "Día de Canarias"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 5, 30, "Día de Canarias"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 5, 30, "Día de Canarias"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 5, 30, "Día de Canarias"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 8, 16, "Lunes siguiente a la Asunción de la Virgen"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 30, "Día de Canarias"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 5, 30, "Día de Canarias"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 5, 30, "Día de Canarias"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 5, 30, "Día de Canarias"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 5, 30, "Día de Canarias"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
]);

/// The days of Cantabria (ES-CB) in the resolutions read.
static CANTABRIA_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 4, 1, "Lunes de Pascua"),
    (2013, 7, 25, "Santiago Apóstol"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 7, 25, "Santiago Apóstol"),
    (2014, 9, 15, "La Bien Aparecida"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 4, 6, "Lunes de Pascua"),
    (2015, 9, 15, "La Bien Aparecida"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (2018, 7, 28, "Día de las Instituciones de Cantabria"),
    (2018, 9, 15, "La Bien Aparecida"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 4, 22, "Lunes de Pascua"),
    (2019, 7, 25, "Santiago Apóstol"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 4, 13, "Lunes de Pascua"),
    (2020, 7, 28, "Día de las Instituciones de Cantabria"),
    (2020, 9, 15, "La Bien Aparecida"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 7, 28, "Día de las Instituciones de Cantabria"),
    (2021, 9, 15, "La Bien Aparecida"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 7, 28, "Día de las Instituciones de Cantabria"),
    (2022, 9, 15, "La Bien Aparecida"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 7, 28, "Día de las Instituciones de Cantabria"),
    (2023, 9, 15, "La Bien Aparecida"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 4, 1, "Lunes de Pascua"),
    (2024, 7, 25, "Santiago Apóstol"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 7, 28, "Día de las Instituciones de Cantabria"),
    (2025, 9, 15, "La Bien Aparecida"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 7, 28, "Día de las Instituciones de Cantabria"),
    (2026, 9, 15, "La Bien Aparecida"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of Castile and León (ES-CL) in the resolutions read.
static CASTILE_AND_LEON_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 4, 23, "Fiesta de Castilla y León"),
    (2013, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 4, 23, "Fiesta de Castilla y León"),
    (
        2014,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 4, 23, "Fiesta de Castilla y León"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 4, 23, "Fiesta de Castilla y León"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 4, 23, "Fiesta de Castilla y León"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 4, 23, "Fiesta de Castilla y León"),
    (2020, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 4, 23, "Fiesta de Castilla y León"),
    (2021, 8, 16, "Lunes siguiente a la Asunción de la Virgen"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 4, 23, "Fiesta de Castilla y León"),
    (2022, 5, 2, "Lunes siguiente a la Fiesta del Trabajo"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 1, 2, "Lunes siguiente a Año Nuevo"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 7, 25, "Santiago Apóstol"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 4, 23, "Fiesta de Castilla y León"),
    (2024, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 4, 23, "Fiesta de Castilla y León"),
    (
        2025,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 4, 23, "Fiesta de Castilla y León"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of Castilla-La Mancha (ES-CM) in the resolutions read.
static CASTILLA_LA_MANCHA_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 5, 30, "Corpus Christi"),
    (2013, 5, 31, "Día de Castilla-La Mancha"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 4, 21, "Lunes de Pascua"),
    (2014, 6, 19, "Corpus Christi"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 4, 6, "Lunes de Pascua"),
    (2015, 6, 4, "Corpus Christi"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 5, 31, "Día de Castilla-La Mancha"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 4, 22, "Lunes de Pascua"),
    (2019, 5, 31, "Día de Castilla-La Mancha"),
    (2019, 6, 20, "Corpus Christi"),
    (2020, 3, 19, "San José"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 4, 13, "Lunes de Pascua"),
    (2020, 6, 11, "Corpus Christi"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 5, 31, "Día de Castilla-La Mancha"),
    (2021, 6, 3, "Corpus Christi"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 31, "Día de Castilla-La Mancha"),
    (2022, 6, 16, "Corpus Christi"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 5, 31, "Día de Castilla-La Mancha"),
    (2023, 6, 8, "Corpus Christi"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 5, 30, "Corpus Christi"),
    (2024, 5, 31, "Día de Castilla-La Mancha"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 5, 31, "Día de Castilla-La Mancha"),
    (2025, 6, 19, "Corpus Christi"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 4, 6, "Lunes de Pascua"),
    (2026, 6, 4, "Corpus Christi"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
]);

/// The days of Catalonia (ES-CT) in the resolutions read.
static CATALONIA_DAYS: Listing = Listing::Named(&[
    (2013, 4, 1, "Lunes de Pascua"),
    (2013, 6, 24, "San Juan"),
    (2013, 9, 11, "Fiesta Nacional de Cataluña"),
    (2013, 12, 26, "San Esteban"),
    (2014, 4, 21, "Lunes de Pascua"),
    (2014, 6, 24, "San Juan"),
    (2014, 9, 11, "Fiesta Nacional de Cataluña"),
    (2014, 12, 26, "San Esteban"),
    (2015, 4, 6, "Lunes de Pascua"),
    (2015, 6, 24, "San Juan"),
    (2015, 9, 11, "Fiesta Nacional de Cataluña"),
    (2015, 12, 26, "San Esteban"),
    (2018, 4, 2, "Lunes de Pascua"),
    (2018, 9, 11, "Fiesta Nacional de Cataluña"),
    (2018, 12, 26, "San Esteban"),
    (2019, 4, 22, "Lunes de Pascua"),
    (2019, 6, 24, "San Juan"),
    (2019, 9, 11, "Fiesta Nacional de Cataluña"),
    (2019, 12, 26, "San Esteban"),
    (2020, 4, 13, "Lunes de Pascua"),
    (2020, 6, 24, "San Juan"),
    (2020, 9, 11, "Fiesta Nacional de Cataluña"),
    (2020, 12, 26, "San Esteban"),
    (2021, 4, 5, "Lunes de Pascua"),
    (2021, 6, 24, "San Juan"),
    (2021, 9, 11, "Fiesta Nacional de Cataluña"),
    (2022, 4, 18, "Lunes de Pascua"),
    (2022, 6, 6, "Lunes de Pascua Granada"),
    (2022, 6, 24, "San Juan"),
    (2022, 12, 26, "San Esteban"),
    (2023, 4, 10, "Lunes de Pascua"),
    (2023, 6, 24, "San Juan"),
    (2023, 9, 11, "Fiesta Nacional de Cataluña"),
    (2023, 12, 26, "San Esteban"),
    (2024, 4, 1, "Lunes de Pascua"),
    (2024, 6, 24, "San Juan"),
    (2024, 9, 11, "Fiesta Nacional de Cataluña"),
    (2024, 12, 26, "San Esteban"),
    (2025, 4, 21, "Lunes de Pascua"),
    (2025, 6, 24, "San Juan"),
    (2025, 9, 11, "Fiesta Nacional de Cataluña"),
    (2025, 12, 26, "San Esteban"),
    (2026, 4, 6, "Lunes de Pascua"),
    (2026, 6, 24, "San Juan"),
    (2026, 9, 11, "Fiesta Nacional de Cataluña"),
    (2026, 12, 26, "San Esteban"),
]);

/// The days of Ceuta (ES-CE) in the resolutions read.
static CEUTA_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 10, 15, "Fiesta del Sacrificio-Eidul Adha"),
    (2013, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 10, 6, "Fiesta del Sacrificio-Eidul Adha"),
    (
        2014,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 9, 25, "Fiesta del Sacrificio-Eidul Adha"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 8, 22, "Fiesta del Sacrificio-Eidul Adha"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 8, 12, "Fiesta del Sacrificio-Eidul Adha"),
    (2019, 9, 2, "Día de Ceuta"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 7, 31, "Fiesta del Sacrificio-Eidul Adha"),
    (2020, 9, 2, "Día de Ceuta"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 7, 20, "Fiesta del Sacrificio-Eidul Adha"),
    (2021, 9, 2, "Día de Ceuta"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 7, 9, "Fiesta del Sacrificio-Eidul Adha"),
    (2022, 8, 5, "Nuestra Señora de África"),
    (2022, 9, 2, "Día de Ceuta"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 6, 29, "Fiesta del Sacrificio-Eidul Adha"),
    (2023, 8, 5, "Nuestra Señora de África"),
    (2023, 9, 2, "Día de Ceuta"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 6, 17, "Fiesta del Sacrificio-Eidul Adha"),
    (2024, 8, 5, "Nuestra Señora de África"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 6, 6, "Fiesta del Sacrificio-Eidul Adha"),
    (2025, 8, 5, "Nuestra Señora de África"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 5, 27, "Fiesta del Sacrificio-Eidul Adha"),
    (2026, 8, 5, "Nuestra Señora de África"),
    (2026, 9, 2, "Día de Ceuta"),
]);

/// The days of the Community of Madrid (ES-MD) in the resolutions read.
static MADRID_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 18, "Traslado de San José"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2014, 6, 19, "Corpus Christi"),
    (2015, 3, 19, "San José"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2015, 6, 4, "Corpus Christi"),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2020, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 3, 19, "San José"),
    (2021, 4, 1, "Jueves Santo"),
    (
        2021,
        5,
        3,
        "Lunes siguiente al Día de la Comunidad de Madrid",
    ),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2022, 7, 25, "Santiago Apóstol"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 3, 20, "Lunes siguiente a San José"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2024, 7, 25, "Santiago Apóstol"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2025, 7, 25, "Santiago Apóstol"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 5, 2, "Fiesta de la Comunidad de Madrid"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of Extremadura (ES-EX) in the resolutions read.
static EXTREMADURA_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 9, 9, "Lunes siguiente al Día de Extremadura"),
    (2013, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 9, 8, "Día de Extremadura"),
    (
        2014,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 9, 8, "Día de Extremadura"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 9, 8, "Día de Extremadura"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 9, 9, "Lunes siguiente al Día de Extremadura"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 9, 8, "Día de Extremadura"),
    (2020, 11, 2, "Lunes siguiente a Todos los Santos"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 3, 19, "San José"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 9, 8, "Día de Extremadura"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 2, "Lunes siguiente a la Fiesta del Trabajo"),
    (2022, 9, 8, "Día de Extremadura"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 2, 21, "Martes de Carnaval"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 9, 8, "Día de Extremadura"),
    (2024, 2, 13, "Martes de Carnaval"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 9, 8, "Día de Extremadura"),
    (
        2025,
        10,
        13,
        "Lunes siguiente a la Fiesta Nacional de España",
    ),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 9, 8, "Día de Extremadura"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of Galicia (ES-GA) in the resolutions read.
static GALICIA_DAYS: Listing = Listing::Named(&[
    (2013, 3, 28, "Jueves Santo"),
    (2013, 5, 17, "Día de las Letras Gallegas"),
    (2013, 6, 24, "San Juan"),
    (2013, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 5, 17, "Día de las Letras Gallegas"),
    (2014, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2015, 3, 20, "Día siguiente a San José"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2015, 11, 2, "Lunes siguiente a Todos los Santos"),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 5, 17, "Día de las Letras Gallegas"),
    (2018, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2019, 3, 19, "San José"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 5, 17, "Día de las Letras Gallegas"),
    (2019, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2020, 3, 19, "San José"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 6, 24, "San Juan"),
    (2020, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2021, 3, 19, "San José"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 5, 17, "Día de las Letras Gallegas"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 17, "Día de las Letras Gallegas"),
    (2022, 6, 24, "San Juan"),
    (2022, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 5, 17, "Día de las Letras Gallegas"),
    (2023, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 5, 17, "Día de las Letras Gallegas"),
    (2024, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 5, 17, "Día de las Letras Gallegas"),
    (2025, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
    (2026, 3, 19, "San José"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 6, 24, "San Juan"),
    (2026, 7, 25, "Santiago Apóstol/Día Nacional de Galicia"),
]);

/// The days of La Rioja (ES-RI) in the resolutions read.
static LA_RIOJA_DAYS: Listing = Listing::Named(&[
    (2013, 3, 28, "Jueves Santo"),
    (2013, 4, 1, "Lunes de Pascua"),
    (2013, 6, 10, "Día de La Rioja"),
    (2013, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 4, 21, "Lunes de Pascua"),
    (2014, 6, 9, "Día de La Rioja"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 4, 6, "Lunes de Pascua"),
    (2015, 6, 9, "Día de La Rioja"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 6, 9, "Día de La Rioja"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 4, 22, "Lunes de Pascua"),
    (2019, 6, 10, "Día de La Rioja"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 4, 13, "Lunes de Pascua"),
    (2020, 6, 9, "Día de La Rioja"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 4, 5, "Lunes de Pascua"),
    (2021, 6, 9, "Día de La Rioja"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 4, 18, "Lunes de Pascua"),
    (2022, 6, 9, "Día de La Rioja"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 4, 10, "Lunes de Pascua"),
    (2023, 6, 9, "Día de La Rioja"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 4, 1, "Lunes de Pascua"),
    (2024, 6, 10, "Lunes siguiente al Día de La Rioja"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 4, 21, "Lunes de Pascua"),
    (2025, 6, 9, "Día de La Rioja"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 4, 6, "Lunes de Pascua"),
    (2026, 6, 9, "Día de La Rioja"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of Melilla (ES-ML) in the resolutions read.
static MELILLA_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 19, "San José"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 10, 15, "Fiesta del Sacrificio-Aid Al Adha"),
    (2014, 3, 19, "San José"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 10, 4, "Fiesta del Sacrificio-Aid Al Adha"),
    (2015, 3, 19, "San José"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 9, 25, "Fiesta del Sacrificio-Aid Al Adha"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 8, 22, "Fiesta del Sacrificio-Aid Al Adha"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 8, 12, "Fiesta del Sacrificio-Aid Al Adha"),
    (2019, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2020, 3, 13, "Estatuto de Autonomía de la Ciudad de Melilla"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 7, 31, "Fiesta del Sacrificio-Aid Al Adha"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 3, 13, "Estatuto de Autonomía de la Ciudad de Melilla"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 7, 21, "Fiesta del Sacrificio-Aid Al Adha"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 3, "Fiesta del Eid Fitr"),
    (2022, 7, 11, "Fiesta del Sacrificio-Aid Al Adha"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 4, 21, "Fiesta del Eid Fitr"),
    (2023, 6, 29, "Fiesta del Sacrificio-Aid Al Adha"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 6, 17, "Fiesta del Sacrificio-Aid Al Adha"),
    (2024, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2025, 3, 31, "Fiesta del Eid Fitr"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 6, 6, "Fiesta del Sacrificio-Aid Al Adha"),
    (2026, 3, 20, "Fiesta del Eid Fitr"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 5, 27, "Fiesta del Sacrificio-Aid Al Adha"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of Navarre (ES-NC) in the resolutions read.
static NAVARRE_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 4, 1, "Lunes de Pascua"),
    (2013, 7, 25, "Santiago Apóstol"),
    (2014, 3, 19, "San José"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 4, 21, "Lunes de Pascua"),
    (2015, 3, 19, "San José"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 4, 6, "Lunes de Pascua"),
    (2015, 7, 25, "Santiago Apóstol"),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 4, 2, "Lunes de Pascua"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 3, 19, "San José"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 4, 22, "Lunes de Pascua"),
    (2020, 3, 19, "San José"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 4, 13, "Lunes de Pascua"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 3, 19, "San José"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 4, 5, "Lunes de Pascua"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 4, 18, "Lunes de Pascua"),
    (2022, 7, 25, "Santiago Apóstol"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 4, 10, "Lunes de Pascua"),
    (2023, 7, 25, "Santiago Apóstol"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 4, 1, "Lunes de Pascua"),
    (2024, 7, 25, "Santiago Apóstol"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 4, 21, "Lunes de Pascua"),
    (2025, 7, 25, "Santiago Apóstol"),
    (2026, 3, 19, "San José"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 4, 6, "Lunes de Pascua"),
    (2026, 11, 2, "Día siguiente a Todos los Santos"),
]);

/// The days of the Region of Murcia (ES-MC) in the resolutions read.
static MURCIA_DAYS: Listing = Listing::Named(&[
    (2013, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2013, 3, 19, "San José"),
    (2013, 3, 28, "Jueves Santo"),
    (2013, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2014, 3, 19, "San José"),
    (2014, 4, 17, "Jueves Santo"),
    (2014, 6, 9, "Día de la Región de Murcia"),
    (2015, 3, 19, "San José"),
    (2015, 4, 2, "Jueves Santo"),
    (2015, 6, 9, "Día de la Región de Murcia"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 19, "San José"),
    (2018, 3, 29, "Jueves Santo"),
    (2018, 6, 9, "Día de la Región de Murcia"),
    (2019, 1, 7, "Lunes siguiente a la Epifanía del Señor"),
    (2019, 3, 19, "San José"),
    (2019, 4, 18, "Jueves Santo"),
    (2019, 6, 10, "Día de la Región de Murcia"),
    (2020, 3, 19, "San José"),
    (2020, 4, 9, "Jueves Santo"),
    (2020, 6, 9, "Día de la Región de Murcia"),
    (
        2020,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2021, 3, 19, "San José"),
    (2021, 4, 1, "Jueves Santo"),
    (2021, 6, 9, "Día de la Región de Murcia"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 5, 2, "Lunes siguiente a la Fiesta del Trabajo"),
    (2022, 6, 9, "Día de la Región de Murcia"),
    (2022, 12, 26, "Lunes siguiente a la Natividad del Señor"),
    (2023, 1, 2, "Lunes siguiente a Año Nuevo"),
    (2023, 4, 6, "Jueves Santo"),
    (2023, 6, 9, "Día de la Región de Murcia"),
    (2024, 3, 19, "San José"),
    (2024, 3, 28, "Jueves Santo"),
    (2024, 12, 9, "Lunes siguiente a la Inmaculada Concepción"),
    (2025, 3, 19, "San José"),
    (2025, 4, 17, "Jueves Santo"),
    (2025, 6, 9, "Día de la Región de Murcia"),
    (2026, 3, 19, "San José"),
    (2026, 4, 2, "Jueves Santo"),
    (2026, 6, 9, "Día de la Región de Murcia"),
    (
        2026,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
]);

/// The days of the Valencian Community (ES-VC) in the resolutions read.
static VALENCIA_DAYS: Listing = Listing::Named(&[
    (2013, 3, 18, "Lunes de Fallas"),
    (2013, 3, 19, "San José"),
    (2013, 4, 1, "Lunes de Pascua"),
    (2013, 10, 9, "Día de la Comunitat Valenciana"),
    (2014, 3, 19, "San José"),
    (2014, 4, 21, "Lunes de Pascua"),
    (2014, 10, 9, "Día de la Comunitat Valenciana"),
    (2015, 3, 19, "San José"),
    (2015, 4, 6, "Lunes de Pascua"),
    (2015, 10, 9, "Día de la Comunitat Valenciana"),
    (
        2015,
        12,
        7,
        "Lunes siguiente al Día de la Constitución Española",
    ),
    (2018, 3, 19, "San José"),
    (2018, 4, 2, "Lunes de Pascua"),
    (2018, 10, 9, "Día de la Comunitat Valenciana"),
    (2019, 3, 19, "San José"),
    (2019, 4, 22, "Lunes de Pascua"),
    (2019, 6, 24, "San Juan"),
    (2019, 10, 9, "Día de la Comunitat Valenciana"),
    (2020, 3, 19, "San José"),
    (2020, 4, 13, "Lunes de Pascua"),
    (2020, 6, 24, "San Juan"),
    (2020, 10, 9, "Día de la Comunitat Valenciana"),
    (2021, 3, 19, "San José"),
    (2021, 4, 5, "Lunes de Pascua"),
    (2021, 6, 24, "San Juan"),
    (2021, 10, 9, "Día de la Comunitat Valenciana"),
    (2022, 3, 19, "San José"),
    (2022, 4, 14, "Jueves Santo"),
    (2022, 4, 18, "Lunes de Pascua"),
    (2022, 6, 24, "San Juan"),
    (2023, 4, 10, "Lunes de Pascua"),
    (2023, 6, 24, "San Juan"),
    (2023, 10, 9, "Día de la Comunitat Valenciana"),
    (2024, 3, 19, "San José"),
    (2024, 4, 1, "Lunes de Pascua"),
    (2024, 6, 24, "San Juan"),
    (2024, 10, 9, "Día de la Comunitat Valenciana"),
    (2025, 3, 19, "San José"),
    (2025, 4, 21, "Lunes de Pascua"),
    (2025, 6, 24, "San Juan"),
    (2025, 10, 9, "Día de la Comunitat Valenciana"),
    (2026, 3, 19, "San José"),
    (2026, 4, 6, "Lunes de Pascua"),
    (2026, 6, 24, "San Juan"),
    (2026, 10, 9, "Día de la Comunitat Valenciana"),
]);
