//! The names of the days of the French Republican year: the *calendrier
//! rural* that put "all the objects that make up the true national wealth"
//! in place of the saints, a plant or fruit on most days, an animal on
//! each *quintidi* and a tool on each *décadi*.
//!
//! Fabre d'Églantine's report of 3 brumaire an II (24 October 1793)
//! explains the names: "the priests had assigned to each day of the year
//! the commemoration of a so-called saint", and "the nation, having driven
//! this crowd of the canonised out of its calendar, should find in their
//! place all the objects that make up the true national wealth"; the
//! decree at its end adopts "the table annexed to this decree" (Fabre
//! d'Églantine, *Rapport ... sur le calendrier*, Imprimerie nationale,
//! 1793, in Wikisource's transcription, `fabre-1793-rapport`, read
//! 2026-09-29). The decree of 4 frimaire an II names only the months and
//! the days of the *décade*; its annexed *annuaire* carried "the names of
//! the days and of the months", and Wikisource's transcription stops before
//! it (`decret-4-frimaire-an-ii`).
//!
//! Two lists, two names (policy §5): [`FABRE_1793`], the table of the
//! report, the one primary list read, and [`IN_USE`], the list both
//! Wikipedias print, French Wikipedia after Millin de Grandmaison's
//! *Annuaire du républicain* (1793–1794), not read
//! (`frwiki-calendrier-republicain`, secondary). They agree on 266 of the
//! 366 names once Fabre's capitals are set in the others' case and his
//! apostrophe is the ASCII one; they differ only in spelling on 42, name
//! different things on 53 — most of Nivôse among them, Fabre's snow, ice,
//! honey and wax becoming peat, coal, bitumen and sulphur, and the sixth
//! complementary day — and call the other five complementary days *Fête*
//! where the list in use has *Jour*. [`ENGLISH`] is
//! English Wikipedia's gloss of each name in [`IN_USE`]
//! (`wikipedia-french-republican-calendar`, secondary), which spells
//! thirteen of the French names differently from French Wikipedia.
//!
//! Each list is 366 names, day 1 of Vendémiaire first, the 360 days of the
//! months and then the six complementary days, the sixth only in a
//! sextile year: [`day_index`] maps a date to its place. Fabre's table
//! prints each *décadi* in capitals and each *quintidi* in small capitals;
//! the names here are in the case of the other days, and its leap day,
//! "LA SANCULOTTIDE", is "La Sanculottide". Its apostrophes are the ASCII
//! one.

/// The position of day `day` of month `month` (13 for the complementary
/// days) in the lists, from 0; `None` for a day no year has.
#[must_use]
pub const fn day_index(month: u8, day: u8) -> Option<usize> {
    match month {
        1..=12 if day >= 1 && day <= 30 => Some((month as usize - 1) * 30 + day as usize - 1),
        13 if day >= 1 && day <= 6 => Some(360 + day as usize - 1),
        _ => None,
    }
}

/// The names in the table annexed to Fabre d'Églantine's report and the
/// decree of 3 brumaire an II (24 October 1793).
pub const FABRE_1793: hc_calendar::shape::Naming<366> = hc_calendar::shape::Naming {
    id: "fr-fabre-1793",
    english_name: "French, Fabre d'Églantine's table of 1793",
    names: &[
        "Raisin",
        "Safran",
        "Châtaignes",
        "Colchique",
        "Cheval",
        "Balsamine",
        "Carottes",
        "Amaranthe",
        "Panais",
        "Cuve",
        "Pomme-de-terre",
        "Immortelle",
        "Potiron",
        "Réséda",
        "Âne",
        "Belle-de-nuit",
        "Citrouille",
        "Sarrasin",
        "Tournesol",
        "Pressoir",
        "Chanvre",
        "Pêche",
        "Navet",
        "Grenesienne",
        "Bœuf",
        "Aubergine",
        "Piment",
        "Tomate",
        "Orge",
        "Tonneau",
        "Pomme",
        "Céleri",
        "Poire",
        "Betterave",
        "Oie",
        "Héliotrope",
        "Figue",
        "Scorsonnère",
        "Alisier",
        "Charrue",
        "Salsifis",
        "Cornuette",
        "Poireterre",
        "Endive",
        "Dindon",
        "Chiroui",
        "Cresson",
        "Dentelaire",
        "Grenade",
        "Herse",
        "Bacchante",
        "Olive",
        "Garence",
        "Orange",
        "Jars",
        "Pistache",
        "Macjonc",
        "Coing",
        "Cormier",
        "Rouleau",
        "Raiponce",
        "Turneps",
        "Chicorée",
        "Nefle",
        "Cochon",
        "Mâche",
        "Chou-fleur",
        "Epicia",
        "Genièvre",
        "Pioche",
        "Thuya",
        "Raifort",
        "Cèdre",
        "Sapin",
        "Laye",
        "Ajonc",
        "Ciprès",
        "Lierre",
        "Bouleau",
        "Hoyau",
        "Érable-sucre",
        "Bruyère",
        "Roseau",
        "Oseille",
        "Grillon",
        "Pignon",
        "Liége",
        "Truffe",
        "Olive",
        "Pelle",
        "Neige",
        "Glace",
        "Miel",
        "Cire",
        "Chien",
        "Fumier",
        "Petrole",
        "Houille",
        "Résine",
        "Fléau",
        "Poix",
        "Thérébentine",
        "Argile",
        "Marne",
        "Lapin",
        "Plâtre",
        "Pierre à chaux",
        "Ardoise",
        "Sable",
        "Van",
        "Grès",
        "Silex",
        "Mercure",
        "Plomb",
        "Chat",
        "Étain",
        "Cuivre",
        "Fer",
        "Sel",
        "Crible",
        "Lauréole",
        "Mousse",
        "Fragon",
        "Perce-neige",
        "Taureau",
        "Laurier-thym",
        "Mnie",
        "Mézéréon",
        "Peuplier",
        "Coignée",
        "Ellébore",
        "Brocoli",
        "Laurier",
        "Coudrier",
        "Vache",
        "Buis",
        "Lichen",
        "If",
        "Pulmonaire",
        "Serpette",
        "Thlaspi",
        "Thymelé",
        "Chiendent",
        "Traînasse",
        "Veau",
        "Gnède",
        "Noisetier",
        "Ciclamen",
        "Chélidoine",
        "Traîneau",
        "Tussilage",
        "Cornouiller",
        "Violier",
        "Troène",
        "Bouc",
        "Asaret",
        "Alaterne",
        "Violette",
        "Marceau",
        "Bêche",
        "Narcisse",
        "Orme",
        "Fumeterre",
        "Vélar",
        "Chèvre",
        "Épinards",
        "Doronic",
        "Mouron",
        "Cerfeuil",
        "Cordeau",
        "Mandragore",
        "Persil",
        "Cochléaria",
        "Pâquerette",
        "Chevreau",
        "Pissenlit",
        "Silvye",
        "Capilaire",
        "Frêne",
        "Plantoir",
        "Prime-vère",
        "Platane",
        "Asperges",
        "Tulipe",
        "Coq",
        "Bette",
        "Bouleau",
        "Jonquille",
        "Aulne",
        "Greffoir",
        "Pervenche",
        "Charme",
        "Morille",
        "Hêtre",
        "Poule",
        "Laitue",
        "Mélèze",
        "Ciguë",
        "Radis",
        "Ruche",
        "Gainier",
        "Romaine",
        "Maronnier",
        "Roquette",
        "Pigeon",
        "Lilas",
        "Anémone",
        "Pensée",
        "Mirthill",
        "Couvoir",
        "Rose",
        "Chêne",
        "Fougère",
        "Aubépine",
        "Abeille",
        "Ancolie",
        "Muguet",
        "Champignon",
        "Hyacinthe",
        "Râteau",
        "Rhubarbe",
        "Sainfoin",
        "Bâton-d'or",
        "Chamérisier",
        "Ver-à-soie",
        "Consoude",
        "Pimprenelle",
        "Corbeille-d'or",
        "Arroche",
        "Sarcloir",
        "Staticé",
        "Fritillaire",
        "Bourrache",
        "Valériane",
        "Carpe",
        "Fusain",
        "Civette",
        "Buglose",
        "Sénevé",
        "Houlette",
        "Luzerne",
        "Hémérocale",
        "Trèfle",
        "Angélique",
        "Canard",
        "Mélisse",
        "Fromental",
        "Martagon",
        "Serpolet",
        "Faulx",
        "Fraise",
        "Bétoine",
        "Pois",
        "Acacia",
        "Canne",
        "Œillet",
        "Sureau",
        "Pavot",
        "Tilleul",
        "Fourche",
        "Barbeau",
        "Camomille",
        "Chèvre-feuille",
        "Caille-lait",
        "Tanche",
        "Jasmin",
        "Verveine",
        "Thym",
        "Pivoine",
        "Chariot",
        "Seigle",
        "Avoine",
        "Oignon",
        "Véronique",
        "Mulet",
        "Romarin",
        "Concombre",
        "Echalottes",
        "Absynthe",
        "Faucille",
        "Coriandre",
        "Artichaut",
        "Giroflée",
        "Lavande",
        "Jumart",
        "Tabac",
        "Groseille",
        "Orge",
        "Cerise",
        "Parc",
        "Menthe",
        "Cumin",
        "Haricots",
        "Orcanète",
        "Pintade",
        "Sauge",
        "Ail",
        "Vesce",
        "Blé",
        "Chalémie",
        "Épeautre",
        "Bouillon-blanc",
        "Melon",
        "Ivroie",
        "Bélier",
        "Prêle",
        "Armoise",
        "Carthame",
        "Mûres",
        "Arrosoir",
        "Panis",
        "Salicot",
        "Abricot",
        "Basilic",
        "Brebis",
        "Guimauve",
        "Lin",
        "Amande",
        "Gentiane",
        "Écluse",
        "Carline",
        "Caprier",
        "Lentille",
        "Aunée",
        "Agneau",
        "Myrte",
        "Colza",
        "Lupin",
        "Coton",
        "Moulin",
        "Prune",
        "Millet",
        "Lycoperde",
        "Escourgeon",
        "Barbeau",
        "Tubéreuse",
        "Sucrion",
        "Apocyn",
        "Réglisse",
        "Échelle",
        "Pastèque",
        "Fenouil",
        "Épine-vinette",
        "Noix",
        "Goujon",
        "Orange",
        "Cardière",
        "Nerprun",
        "Sagette",
        "Hotte",
        "Églantier",
        "Noisette",
        "Houblon",
        "Sorgho",
        "Écrevisse",
        "Bigarade",
        "Verge-d'or",
        "Maïs",
        "Marron",
        "Corbeille",
        "Fête de la Vertu",
        "Fête du Génie",
        "Fête du Travail",
        "Fête de l'Opinion",
        "Fête des Récompenses",
        "La Sanculottide",
    ],
    authority: "Fabre d'Églantine, Rapport sur le calendrier, 3 brumaire an II (24 October 1793), the annexed table, in Wikisource's transcription, retrieved 2026-09-29",
};

/// The names as the calendar came to use them, as French Wikipedia lists
/// them after Millin de Grandmaison's *Annuaire du républicain*.
pub const IN_USE: hc_calendar::shape::Naming<366> = hc_calendar::shape::Naming {
    id: "fr",
    english_name: "French",
    names: &[
        "Raisin",
        "Safran",
        "Châtaigne",
        "Colchique",
        "Cheval",
        "Balsamine",
        "Carotte",
        "Amarante",
        "Panais",
        "Cuve",
        "Pomme de terre",
        "Immortelle",
        "Potiron",
        "Réséda",
        "Âne",
        "Belle-de-nuit",
        "Citrouille",
        "Sarrasin",
        "Tournesol",
        "Pressoir",
        "Chanvre",
        "Pêche",
        "Navet",
        "Amaryllis",
        "Bœuf",
        "Aubergine",
        "Piment",
        "Tomate",
        "Orge",
        "Tonneau",
        "Pomme",
        "Céleri",
        "Poire",
        "Betterave",
        "Oie",
        "Héliotrope",
        "Figue",
        "Scorsonère",
        "Alisier",
        "Charrue",
        "Salsifis",
        "Mâcre",
        "Topinambour",
        "Endive",
        "Dindon",
        "Chervis",
        "Cresson",
        "Dentelaire",
        "Grenade",
        "Herse",
        "Bacchante",
        "Azerole",
        "Garance",
        "Orange",
        "Faisan",
        "Pistache",
        "Macjonc",
        "Coing",
        "Cormier",
        "Rouleau",
        "Raiponce",
        "Turneps",
        "Chicorée",
        "Nèfle",
        "Cochon",
        "Mâche",
        "Chou-fleur",
        "Miel",
        "Genièvre",
        "Pioche",
        "Cire",
        "Raifort",
        "Cèdre",
        "Sapin",
        "Chevreuil",
        "Ajonc",
        "Cyprès",
        "Lierre",
        "Sabine",
        "Hoyau",
        "Érable sucré",
        "Bruyère",
        "Roseau",
        "Oseille",
        "Grillon",
        "Pignon",
        "Liège",
        "Truffe",
        "Olive",
        "Pelle",
        "Tourbe",
        "Houille",
        "Bitume",
        "Soufre",
        "Chien",
        "Lave",
        "Terre végétale",
        "Fumier",
        "Salpêtre",
        "Fléau",
        "Granit",
        "Argile",
        "Ardoise",
        "Grès",
        "Lapin",
        "Silex",
        "Marne",
        "Pierre à chaux",
        "Marbre",
        "Van",
        "Pierre à plâtre",
        "Sel",
        "Fer",
        "Cuivre",
        "Chat",
        "Étain",
        "Plomb",
        "Zinc",
        "Mercure",
        "Crible",
        "Lauréole",
        "Mousse",
        "Fragon",
        "Perce neige",
        "Taureau",
        "Laurier thym",
        "Amadouvier",
        "Mézéréon",
        "Peuplier",
        "Cognée",
        "Ellébore",
        "Brocoli",
        "Laurier",
        "Avelinier",
        "Vache",
        "Buis",
        "Lichen",
        "If",
        "Pulmonaire",
        "Serpette",
        "Thlaspi",
        "Thymèle",
        "Chiendent",
        "Trainasse",
        "Lièvre",
        "Guède",
        "Noisetier",
        "Cyclamen",
        "Chélidoine",
        "Traîneau",
        "Tussilage",
        "Cornouiller",
        "Violier",
        "Troène",
        "Bouc",
        "Asaret",
        "Alaterne",
        "Violette",
        "Marceau",
        "Bêche",
        "Narcisse",
        "Orme",
        "Fumeterre",
        "Vélar",
        "Chèvre",
        "Épinard",
        "Doronic",
        "Mouron",
        "Cerfeuil",
        "Cordeau",
        "Mandragore",
        "Persil",
        "Cochléaria",
        "Pâquerette",
        "Thon",
        "Pissenlit",
        "Sylvie",
        "Capillaire",
        "Frêne",
        "Plantoir",
        "Primevère",
        "Platane",
        "Asperge",
        "Tulipe",
        "Poule",
        "Bette",
        "Bouleau",
        "Jonquille",
        "Aulne",
        "Couvoir",
        "Pervenche",
        "Charme",
        "Morille",
        "Hêtre",
        "Abeille",
        "Laitue",
        "Mélèze",
        "Ciguë",
        "Radis",
        "Ruche",
        "Gainier",
        "Romaine",
        "Marronnier",
        "Roquette",
        "Pigeon",
        "Lilas",
        "Anémone",
        "Pensée",
        "Myrtille",
        "Greffoir",
        "Rose",
        "Chêne",
        "Fougère",
        "Aubépine",
        "Rossignol",
        "Ancolie",
        "Muguet",
        "Champignon",
        "Hyacinthe",
        "Râteau",
        "Rhubarbe",
        "Sainfoin",
        "Bâton-d'or",
        "Chamérisier",
        "Ver à soie",
        "Consoude",
        "Pimprenelle",
        "Corbeille d'or",
        "Arroche",
        "Sarcloir",
        "Statice",
        "Fritillaire",
        "Bourrache",
        "Valériane",
        "Carpe",
        "Fusain",
        "Civette",
        "Buglosse",
        "Sénevé",
        "Houlette",
        "Luzerne",
        "Hémérocalle",
        "Trèfle",
        "Angélique",
        "Canard",
        "Mélisse",
        "Fromental",
        "Martagon",
        "Serpolet",
        "Faux",
        "Fraise",
        "Bétoine",
        "Pois",
        "Acacia",
        "Caille",
        "Œillet",
        "Sureau",
        "Pavot",
        "Tilleul",
        "Fourche",
        "Barbeau",
        "Camomille",
        "Chèvrefeuille",
        "Caille-lait",
        "Tanche",
        "Jasmin",
        "Verveine",
        "Thym",
        "Pivoine",
        "Chariot",
        "Seigle",
        "Avoine",
        "Oignon",
        "Véronique",
        "Mulet",
        "Romarin",
        "Concombre",
        "Échalote",
        "Absinthe",
        "Faucille",
        "Coriandre",
        "Artichaut",
        "Giroflée",
        "Lavande",
        "Chamois",
        "Tabac",
        "Groseille",
        "Gesse",
        "Cerise",
        "Parc",
        "Menthe",
        "Cumin",
        "Haricot",
        "Orcanète",
        "Pintade",
        "Sauge",
        "Ail",
        "Vesce",
        "Blé",
        "Chalemie",
        "Épeautre",
        "Bouillon-blanc",
        "Melon",
        "Ivraie",
        "Bélier",
        "Prêle",
        "Armoise",
        "Carthame",
        "Mûre",
        "Arrosoir",
        "Panic",
        "Salicorne",
        "Abricot",
        "Basilic",
        "Brebis",
        "Guimauve",
        "Lin",
        "Amande",
        "Gentiane",
        "Écluse",
        "Carline",
        "Câprier",
        "Lentille",
        "Aunée",
        "Loutre",
        "Myrte",
        "Colza",
        "Lupin",
        "Coton",
        "Moulin",
        "Prune",
        "Millet",
        "Lycoperdon",
        "Escourgeon",
        "Saumon",
        "Tubéreuse",
        "Sucrion",
        "Apocyn",
        "Réglisse",
        "Échelle",
        "Pastèque",
        "Fenouil",
        "Épine-vinette",
        "Noix",
        "Truite",
        "Citron",
        "Cardère",
        "Nerprun",
        "Tagette",
        "Hotte",
        "Églantier",
        "Noisette",
        "Houblon",
        "Sorgho",
        "Écrevisse",
        "Bigarade",
        "Verge d'or",
        "Maïs",
        "Marron",
        "Panier",
        "Jour de la Vertu",
        "Jour du Génie",
        "Jour du Travail",
        "Jour de l'Opinion",
        "Jour des Récompenses",
        "Jour de la Révolution",
    ],
    authority: "French Wikipedia, \"Calendrier républicain\", retrieved 2026-09-29, after Millin de Grandmaison, Annuaire du républicain (1793–1794), not read",
};

/// English Wikipedia's English for each name of [`IN_USE`].
pub const ENGLISH: hc_calendar::shape::Naming<366> = hc_calendar::shape::Naming {
    id: "en",
    english_name: "English",
    names: &[
        "Grape",
        "Saffron",
        "Chestnut",
        "Autumn Crocus",
        "Horse",
        "Impatiens",
        "Carrot",
        "Amaranth",
        "Parsnip",
        "Vat",
        "Potato",
        "Strawflower",
        "Winter squash",
        "Mignonette",
        "Donkey",
        "Four o'clock flower",
        "Pumpkin",
        "Buckwheat",
        "Sunflower",
        "Winepress",
        "Hemp",
        "Peach",
        "Turnip",
        "Amaryllis",
        "Ox",
        "Eggplant",
        "Chili pepper",
        "Tomato",
        "Barley",
        "Barrel",
        "Apple",
        "Celery",
        "Pear",
        "Beetroot",
        "Goose",
        "Heliotrope",
        "Common fig",
        "Black Salsify",
        "Chequer Tree",
        "Plough",
        "Salsify",
        "Water caltrop",
        "Jerusalem artichoke",
        "Endive",
        "Turkey",
        "Skirret",
        "Watercress",
        "Leadworts",
        "Pomegranate",
        "Harrow",
        "Baccharis",
        "Azarole",
        "Madder",
        "Orange",
        "Pheasant",
        "Pistachio Nut",
        "Tuberous pea",
        "Quince",
        "Service tree",
        "Roller",
        "Rampion",
        "Cattle turnip",
        "Chicory",
        "Medlar",
        "Pig",
        "Lamb's lettuce",
        "Cauliflower",
        "Honey",
        "Juniper",
        "Pickaxe",
        "Wax",
        "Horseradish",
        "Cedar tree",
        "Fir",
        "Roe deer",
        "Gorse",
        "Cypress Tree",
        "Ivy",
        "Savin Juniper",
        "Fork hoe",
        "Sugar Maple",
        "Heather",
        "Reed plant",
        "Sorrel",
        "Cricket",
        "Pine nut",
        "Cork",
        "Truffle",
        "Olive",
        "Shovel",
        "Peat",
        "Coal",
        "Bitumen",
        "Sulphur",
        "Dog",
        "Lava",
        "Topsoil",
        "Manure",
        "Saltpeter",
        "Flail",
        "Granite",
        "Clay",
        "Slate",
        "Sandstone",
        "Rabbit",
        "Flint",
        "Marl",
        "Limestone",
        "Marble",
        "Winnowing fan",
        "Gypsum",
        "Salt",
        "Iron",
        "Copper",
        "Cat",
        "Tin",
        "Lead",
        "Zinc",
        "Mercury",
        "Sieve",
        "Spurge-laurel",
        "Moss",
        "Butcher's Broom",
        "Snowdrop",
        "Bull",
        "Laurustinus",
        "Tinder polypore",
        "Daphne mezereum",
        "Poplar",
        "Axe",
        "Hellebore",
        "Broccoli",
        "Bay laurel",
        "Filbert",
        "Cow",
        "Box Tree",
        "Lichen",
        "Yew tree",
        "Lungwort",
        "Billhook",
        "Pennycress",
        "Rose Daphne",
        "Couch grass",
        "Common Knotgrass",
        "Hare",
        "Woad",
        "Hazel",
        "Cyclamen",
        "Celandine",
        "Sleigh",
        "Coltsfoot",
        "Dogwood",
        "Matthiola",
        "Privet",
        "Billygoat",
        "Wild Ginger",
        "Italian Buckthorn",
        "Violet",
        "Goat Willow",
        "Spade",
        "Narcissus",
        "Elm",
        "Common fumitory",
        "Hedge mustard",
        "Goat",
        "Spinach",
        "Doronicum",
        "Pimpernel",
        "Chervil",
        "Twine",
        "Mandrake",
        "Parsley",
        "Scurvy-grass",
        "Daisy",
        "Tuna",
        "Dandelion",
        "Wood Anemone",
        "Maidenhair fern",
        "Ash tree",
        "Dibber",
        "Primrose",
        "Plane Tree",
        "Asparagus",
        "Tulip",
        "Hen",
        "Chard",
        "Birch",
        "Daffodil",
        "Alder",
        "Incubator",
        "Periwinkle",
        "Hornbeam",
        "Morel",
        "Beech Tree",
        "Bee",
        "Lettuce",
        "Larch",
        "Hemlock",
        "Radish",
        "Beehive",
        "Judas tree",
        "Romaine lettuce",
        "Horse chestnut",
        "Arugula or Rocket",
        "Pigeon",
        "Lilac",
        "Wood Anemone",
        "Pansy",
        "Bilberry",
        "Grafting knife",
        "Rose",
        "Oak Tree",
        "Fern",
        "Hawthorn",
        "Nightingale",
        "Common Columbine",
        "Lily of the valley",
        "Button mushroom",
        "Hyacinth",
        "Rake",
        "Rhubarb",
        "Sainfoin",
        "Wallflower",
        "Fan Palm tree",
        "Silkworm",
        "Comfrey",
        "Salad burnet",
        "Basket of Gold",
        "Orache",
        "Weeding hoe",
        "Sea thrift",
        "Fritillary",
        "Borage",
        "Valerian",
        "Carp",
        "Euonymus",
        "Chives",
        "Bugloss",
        "White mustard",
        "Shepherd's crook",
        "Lucerne",
        "Daylily",
        "Clover",
        "Garden Angelica",
        "Duck",
        "Lemon balm",
        "Oat grass",
        "Martagon lily",
        "Wild Thyme",
        "Scythe",
        "Strawberry",
        "Betony",
        "Pea",
        "Acacia",
        "Quail",
        "Carnation",
        "Elderberry",
        "Poppy plant",
        "Linden or Lime tree",
        "Pitchfork",
        "Cornflower",
        "Camomile",
        "Honeysuckle",
        "Bedstraw",
        "Tench",
        "Jasmine",
        "Vervain",
        "Thyme",
        "Peony",
        "Handcart",
        "Rye",
        "Oat",
        "Onion",
        "Speedwell",
        "Mule",
        "Rosemary",
        "Cucumber",
        "Shallot",
        "Wormwood",
        "Sickle",
        "Coriander",
        "Artichoke",
        "Clove",
        "Lavender",
        "Chamois",
        "Tobacco",
        "Redcurrant",
        "Hairy Vetchling",
        "Cherry",
        "Livestock pen",
        "Mint",
        "Cumin",
        "Bean",
        "Alkanet",
        "Guineafowl",
        "Sage",
        "Garlic",
        "Tare",
        "Wheat",
        "Shawm",
        "Spelt",
        "Common mullein",
        "Melon",
        "Ryegrass",
        "Ram",
        "Horsetail",
        "Mugwort",
        "Safflower",
        "Blackberry",
        "Watering can",
        "Foxtail millet",
        "Common Glasswort",
        "Apricot",
        "Basil",
        "Ewe",
        "Marshmallow",
        "Flax",
        "Almond",
        "Gentian",
        "Lock",
        "Carline thistle",
        "Caper",
        "Lentil",
        "Inula",
        "Otter",
        "Myrtle",
        "Rapeseed",
        "Lupin",
        "Cotton",
        "Mill",
        "Plum",
        "Millet",
        "Puffball",
        "Six-row Barley",
        "Salmon",
        "Tuberose",
        "Winter Barley",
        "Apocynum",
        "Liquorice",
        "Ladder",
        "Watermelon",
        "Fennel",
        "European Barberry",
        "Walnut",
        "Trout",
        "Lemon",
        "Teasel",
        "Buckthorn",
        "Mexican Marigold",
        "Harvesting basket",
        "Wild Rose",
        "Hazelnut",
        "Hops",
        "Sorghum",
        "Crayfish",
        "Bitter orange",
        "Goldenrod",
        "Maize or Corn",
        "Sweet Chestnut",
        "Pack Basket",
        "Celebration of Virtue",
        "Celebration of Talent",
        "Celebration of Labour",
        "Celebration of Convictions",
        "Celebration of Honours (Awards)",
        "Celebration of the Revolution",
    ],
    authority: "English Wikipedia, \"French Republican calendar\", retrieved 2026-09-29",
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_lists_are_where_their_sources_put_them() {
        let name = |list: &hc_calendar::shape::Naming<366>, month, day| {
            list.name(day_index(month, day).unwrap())
        };
        // Larousse's pairs of a saint's day and the Republican day: François
        // on 13 vendémiaire, Potiron; Catherine on 5 frimaire, Cochon;
        // Victor on 3 thermidor, Melon; Frédéric on 8 floréal, Champignon;
        // Prosper on 7 messidor, Concombre; Zacharie on 15 brumaire,
        // Dindon (Grand dictionnaire universel, t. 3, 1867, secondary).
        for (month, day, expected) in [
            (1, 13, "Potiron"),
            (3, 5, "Cochon"),
            (11, 3, "Melon"),
            (8, 8, "Champignon"),
            (10, 7, "Concombre"),
            (2, 15, "Dindon"),
        ] {
            assert_eq!(name(&IN_USE, month, day), expected);
            assert_eq!(name(&FABRE_1793, month, day), expected);
        }
        assert_eq!(name(&IN_USE, 1, 1), "Raisin");
        assert_eq!(name(&ENGLISH, 1, 1), "Grape");
        assert_eq!(name(&IN_USE, 4, 1), "Tourbe");
        assert_eq!(name(&FABRE_1793, 4, 1), "Neige");
        assert_eq!(name(&IN_USE, 12, 30), "Panier");
        assert_eq!(name(&FABRE_1793, 12, 30), "Corbeille");
        assert_eq!(name(&IN_USE, 13, 6), "Jour de la Révolution");
        assert_eq!(name(&FABRE_1793, 13, 6), "La Sanculottide");
        assert_eq!(name(&FABRE_1793, 13, 1), "Fête de la Vertu");
        assert_eq!(day_index(13, 7), None);
        assert_eq!(day_index(1, 31), None);
        assert_eq!(day_index(0, 1), None);
        assert_eq!(day_index(12, 30), Some(359));
        let differ = (0..366)
            .filter(|index| IN_USE.name(*index) != FABRE_1793.name(*index))
            .count();
        assert_eq!(differ, 100);
    }
}
