//! What a locale calls a calendar CLDR has no name for, where a source in
//! that language names it.
//!
//! CLDR names the calendars of its own `-u-ca-` keys, and [`crate::names`]
//! reads those from each locale's data first. The registry carries many
//! more, and a name for one of them is only here when a source written in
//! the language names that calendar; every other one keeps its English
//! name, the calendar's own, so that nothing is translated or invented.
//! Two tables answer, in this order:
//!
//! 1. [`SOURCED_CALENDAR_NAMES`], written by hand from a page read in the
//!    language. The Tibetan almanac's calendars are these:
//!    - `tibetan`, the Phugpa reckoning, "浦派为藏地官方历书所采用", the one
//!      the official almanacs use, bears the name of the Tibetan calendar
//!      itself: 藏历 and 藏曆 (Chinese Wikipedia, 藏曆, revision 91955698,
//!      read 2026-09-29, `wikipedia-zh-tibetan-calendar`, in its zh-Hans and
//!      zh-Hant variants), チベット暦 (Japanese Wikipedia, revision
//!      90277485, `wikipedia-ja-tibetan-calendar`) and བོད་ཀྱི་ལོ་ཐོ (Tibetan
//!      Wikipedia's title, revision 133632, `wikipedia-bo-tibetan-calendar`).
//!    - `tibetan-tsurphu` is the reckoning of the Tsurphu school, which the
//!      Chinese article names 楚尔派 (楚爾派), "མཚུར་ལུགས་, mtshur lugs".
//!    - `mongolian`, the Tögs buyant reckoning of 1747, is the traditional
//!      Mongolian calendar: モンゴル暦 (Japanese Wikipedia, revision
//!      87251925, `wikipedia-ja-mongolian-calendar`), 蒙古历 and 蒙古曆
//!      (Chinese Wikipedia, 蒙古历, revision 87459686,
//!      `wikipedia-zh-mongolian-calendar`), and Билгийн тоолол, the
//!      "traditional lunar reckoning" beside the Gregorian Аргын тоолол
//!      (Mongolian Wikipedia, Монгол цаг тоолол, revision 817498,
//!      `wikipedia-mn-mongolian-calendar`, and the Japanese article).
//! 2. [`crate::data::WIKIPEDIA_CALENDAR_NAMES`], generated by
//!    `scripts/calendar-names-wikipedia.py` from the interlanguage links of
//!    Wikipedia's articles on the calendars: each carried locale's title of
//!    its own edition's article on a calendar, exactly as that edition
//!    writes it (`wikipedia-calendar-names`). The module's documentation
//!    lists the articles read, with their revisions, the calendars no
//!    article names and the locales no edition writes.
//!
//! A calendar neither table names in a locale has no name there, and
//! `hc_calendars` and `hc_calendar_list` show its English name with an
//! empty locale-used cell, as before: the Bhutanese reckonings, both Lochen
//! variants and the Tsurphu karaṇa Sun in every language, the Mongolian
//! calendar in Tibetan, and the Tibetan ones in Mongolian among them.

use hc_calendar::CalendarId;

use crate::names::CalendarDisplayName;

/// The hand-written names, each with the tag of the locale data it belongs
/// to.
pub const SOURCED_CALENDAR_NAMES: &[(&str, CalendarDisplayName)] = &[
    ("bo", CalendarDisplayName::new("tibetan", "བོད་ཀྱི་ལོ་ཐོ")),
    ("bo", CalendarDisplayName::new("tibetan-tsurphu", "མཚུར་ལུགས")),
    ("ja", CalendarDisplayName::new("tibetan", "チベット暦")),
    ("ja", CalendarDisplayName::new("mongolian", "モンゴル暦")),
    (
        "mn",
        CalendarDisplayName::new("mongolian", "Билгийн тоолол"),
    ),
    ("zh-Hans", CalendarDisplayName::new("tibetan", "藏历")),
    (
        "zh-Hans",
        CalendarDisplayName::new("tibetan-tsurphu", "楚尔派"),
    ),
    ("zh-Hans", CalendarDisplayName::new("mongolian", "蒙古历")),
    ("zh-Hant", CalendarDisplayName::new("tibetan", "藏曆")),
    (
        "zh-Hant",
        CalendarDisplayName::new("tibetan-tsurphu", "楚爾派"),
    ),
    ("zh-Hant", CalendarDisplayName::new("mongolian", "蒙古曆")),
];

/// The name the locale data tagged `tag` has for `calendar` here, if any:
/// the hand-written one first, then the generated Wikipedia title.
#[must_use]
pub fn sourced_calendar_name(tag: &str, calendar: CalendarId) -> Option<&'static str> {
    SOURCED_CALENDAR_NAMES
        .iter()
        .find(|(entry_tag, entry)| *entry_tag == tag && entry.calendar == calendar)
        .map(|(_, entry)| entry.name)
        .or_else(|| wikipedia_calendar_name(tag, calendar))
}

/// The Wikipedia title the locale data tagged `tag` carries for `calendar`,
/// if any.
#[must_use]
pub fn wikipedia_calendar_name(tag: &str, calendar: CalendarId) -> Option<&'static str> {
    let at = crate::data::WIKIPEDIA_CALENDAR_NAMES
        .binary_search_by(|(entry_tag, _)| entry_tag.cmp(&tag))
        .ok()?;
    crate::data::WIKIPEDIA_CALENDAR_NAMES[at]
        .1
        .iter()
        .find(|entry| entry.calendar == calendar)
        .map(|entry| entry.name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Locale;
    use crate::data::{LOCALES, WIKIPEDIA_CALENDAR_NAMES};
    use crate::names::calendar_display_name_with_tag;

    fn named(tag: &str, calendar: &'static str) -> Option<(&'static str, &'static str)> {
        calendar_display_name_with_tag(&Locale::parse(tag).expect("a tag"), CalendarId(calendar))
    }

    fn entry(tag: &str) -> &'static crate::names::LocaleData {
        LOCALES
            .iter()
            .find(|data| data.tag == tag)
            .expect("carried")
    }

    /// The names are found through each locale's fallback, a region's
    /// tag answering with its language's data, and a calendar CLDR names
    /// keeps CLDR's name.
    #[test]
    fn the_tibetan_almanacs_calendars_are_named_where_a_source_names_them() {
        assert_eq!(named("zh-Hans", "tibetan"), Some(("藏历", "zh-Hans")));
        assert_eq!(
            named("zh-TW", "tibetan-tsurphu"),
            Some(("楚爾派", "zh-Hant"))
        );
        assert_eq!(named("ja-JP", "mongolian"), Some(("モンゴル暦", "ja")));
        assert_eq!(named("mn", "mongolian"), Some(("Билгийн тоолол", "mn")));
        assert_eq!(named("bo", "tibetan"), Some(("བོད་ཀྱི་ལོ་ཐོ", "bo")));
        assert_eq!(named("ja", "japanese"), Some(("和暦", "ja")));
        // No source names the Bhutanese reckoning in Japanese.
        assert_ne!(
            named("ja", "tibetan-bhutan").map(|(_, tag)| tag),
            Some("ja")
        );
        for (tag, entry) in SOURCED_CALENDAR_NAMES {
            let data = self::entry(tag);
            // CLDR's own name would come first, so none is shadowed.
            assert!(
                data.calendar_names
                    .iter()
                    .all(|cldr| cldr.calendar != entry.calendar),
                "{tag} {}",
                entry.calendar.0
            );
        }
    }

    /// The generated titles fill what CLDR and the hand-written entries
    /// leave: each under a carried tag, sorted so that the lookup can
    /// search them, none for a calendar those name already, none equal to
    /// the identifier, and no two calendars of a locale under one name.
    #[test]
    fn the_wikipedia_titles_fill_what_the_other_tables_leave() {
        assert_eq!(named("ja", "burmese"), Some(("ビルマ暦", "ja")));
        assert_eq!(named("de-AT", "maya-haab"), Some(("Haab", "de")));
        assert_eq!(named("zh-Hans", "burmese"), Some(("缅历", "zh-Hans")));
        assert_eq!(named("zh-HK", "burmese"), Some(("緬曆", "zh-Hant")));
        // CLDR's and the hand-written names still answer first.
        assert_eq!(named("ja", "gregory"), Some(("西暦(グレゴリオ暦)", "ja")));
        assert_eq!(named("ja", "tibetan"), Some(("チベット暦", "ja")));
        assert!(
            WIKIPEDIA_CALENDAR_NAMES
                .windows(2)
                .all(|pair| pair[0].0 < pair[1].0),
            "sorted by tag"
        );
        for (tag, titles) in WIKIPEDIA_CALENDAR_NAMES {
            let data = entry(tag);
            let mut seen: alloc::collections::BTreeMap<&str, &str> =
                alloc::collections::BTreeMap::new();
            for cldr in data.calendar_names {
                seen.insert(cldr.name, cldr.calendar.0);
            }
            for (hand_tag, hand) in SOURCED_CALENDAR_NAMES {
                if hand_tag == tag {
                    seen.insert(hand.name, hand.calendar.0);
                }
            }
            for title in *titles {
                assert!(
                    !title.name.is_empty() && title.name != title.calendar.0,
                    "{tag}"
                );
                assert!(
                    data.calendar_names
                        .iter()
                        .all(|cldr| cldr.calendar != title.calendar),
                    "{tag} {}: CLDR names it",
                    title.calendar.0
                );
                assert!(
                    SOURCED_CALENDAR_NAMES
                        .iter()
                        .all(|(hand_tag, hand)| hand_tag != tag || hand.calendar != title.calendar),
                    "{tag} {}: a hand-written entry names it",
                    title.calendar.0
                );
                if let Some(other) = seen.insert(title.name, title.calendar.0) {
                    panic!(
                        "{tag}: {} names {other} and {}",
                        title.name, title.calendar.0
                    );
                }
            }
        }
    }
}
