//! Renders the export tables in the two boundary crates' READMEs and fails
//! when the committed tables have drifted from the source.
//!
//! The C ABI and the WebAssembly surface are the two places a caller who
//! cannot be assumed to read Rust meets this library, so their READMEs have
//! to list every export with its signature. A hand-written list is the kind
//! of document that is right on the day it is written. These are rendered
//! from the sources of each crate, spliced between two markers in the
//! README, and compared, so an entry point without a row — or a row without
//! an entry point — fails the build. The prose around the markers is
//! written; only the tables are generated.
//!
//! The exports are read as `support/boundaries.rs` reads them: each
//! crate's own functions, and the rows of the facade's table of shared
//! exports, `src/exports.rs`, where a layer module expands them. Each row
//! also names the Cargo feature the export is behind, the one on the
//! module that holds it or expands it, so the table says which layer a
//! caller has to build.
//!
//! To accept a change: `UPDATE_ABI=1 cargo test -p hyper-calendar --test
//! abi`, then read the diff before committing it.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

#[path = "support/boundaries.rs"]
mod boundaries;

use boundaries::{Export, Side};

const FFI_CRATE: &str = "../hyper-calendar-ffi";
const FFI_SOURCE: &str = "../hyper-calendar-ffi/src/lib.rs";
const FFI_README: &str = "../hyper-calendar-ffi/README.md";
const WASM_CRATE: &str = "../hyper-calendar-wasm";
const WASM_SOURCE: &str = "../hyper-calendar-wasm/src/lib.rs";
const WASM_README: &str = "../hyper-calendar-wasm/README.md";

const START: &str = "<!-- generated by crates/hyper-calendar/tests/abi.rs: start -->";
const END: &str = "<!-- generated by crates/hyper-calendar/tests/abi.rs: end -->";

/// One `pub const` status code or sentinel.
struct Code {
    name: String,
    value: String,
    summary: String,
}

fn read(path: &str) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|error| panic!("could not read {path}: {error}"))
}

/// The doc lines immediately above `index`, oldest first.
fn docs_above<'a>(lines: &[&'a str], index: usize) -> Vec<&'a str> {
    let mut docs = Vec::new();
    let mut cursor = index;
    while cursor > 0 && lines[cursor - 1].trim_start().starts_with("///") {
        cursor -= 1;
        docs.push(lines[cursor].trim_start().trim_start_matches("///").trim());
    }
    docs.reverse();
    docs
}

/// The first paragraph of a doc comment, as one line.
fn summary_of(docs: &[&str]) -> String {
    // Intra-doc links are Markdown for rustdoc, not for a README.
    docs.iter()
        .take_while(|line| !line.is_empty())
        .copied()
        .collect::<Vec<_>>()
        .join(" ")
        .replace("[`", "`")
        .replace("`]", "`")
}

/// Every export of a boundary, in order: its own, and the facade table's
/// rows where it expands them.
fn exports(side: Side) -> Vec<Export> {
    let crate_dir = match side {
        Side::C => FFI_CRATE,
        Side::Wasm => WASM_CRATE,
    };
    boundaries::exports(Path::new(crate_dir), Path::new("."), side)
}

/// The feature cell of a row: the feature's name in code, or `always`.
fn feature_cell(export: &Export) -> String {
    if export.feature == "always" {
        "always".to_owned()
    } else {
        format!("`{}`", export.feature)
    }
}

/// Every `pub const` whose name starts with `prefix`, with its doc summary.
fn codes(source: &str, prefix: &str) -> Vec<Code> {
    let lines: Vec<&str> = source.lines().collect();
    let mut out = Vec::new();
    for (index, line) in lines.iter().enumerate() {
        let Some(rest) = line.strip_prefix("pub const ") else {
            continue;
        };
        if !rest.starts_with(prefix) {
            continue;
        }
        let Some((name, rest)) = rest.split_once(':') else {
            panic!("constant without a type on line {}", index + 1)
        };
        let Some((_, value)) = rest.split_once('=') else {
            panic!("constant without a value on line {}", index + 1)
        };
        out.push(Code {
            name: name.trim().to_owned(),
            value: value.trim().trim_end_matches(';').trim().to_owned(),
            summary: summary_of(&docs_above(&lines, index)),
        });
    }
    assert!(!out.is_empty(), "no constants with prefix {prefix}");
    out
}

/// The C spelling of a Rust type used at the boundary.
///
/// Unknown types are a panic on purpose: a new type at the boundary needs a
/// C name decided by a person, not guessed by a table.
fn c_type(rust: &str) -> String {
    match rust {
        "i64" => "int64_t".to_owned(),
        "u64" => "uint64_t".to_owned(),
        "f64" => "double".to_owned(),
        "i32" => "int32_t".to_owned(),
        "u32" => "uint32_t".to_owned(),
        "u16" => "uint16_t".to_owned(),
        "u8" => "uint8_t".to_owned(),
        "usize" => "size_t".to_owned(),
        "c_int" => "int".to_owned(),
        "c_char" => "char".to_owned(),
        "HcStatus" => "HcStatus".to_owned(),
        _ => {
            if let Some(inner) = rust.strip_prefix("*mut ") {
                format!("{} *", c_type(inner))
            } else if let Some(inner) = rust.strip_prefix("*const ") {
                format!("const {} *", c_type(inner))
            } else {
                panic!("no C spelling for `{rust}`; add one to c_type")
            }
        }
    }
}

/// A C prototype for an export.
fn prototype(export: &Export) -> String {
    let params: Vec<String> = export
        .params
        .iter()
        .map(|(name, ty)| {
            let ty = c_type(ty);
            if ty.ends_with('*') {
                format!("{ty}{name}")
            } else {
                format!("{ty} {name}")
            }
        })
        .collect();
    let returns = export.returns.as_deref().map_or("void".to_owned(), c_type);
    format!("{returns} {}({});", export.name, params.join(", "))
}

/// A Rust-typed signature for a WebAssembly export.
fn wasm_signature(export: &Export) -> String {
    let params: Vec<String> = export
        .params
        .iter()
        .map(|(name, ty)| format!("{name}: {ty}"))
        .collect();
    match &export.returns {
        Some(ret) => format!("{}({}) -> {ret}", export.name, params.join(", ")),
        None => format!("{}({})", export.name, params.join(", ")),
    }
}

fn render_ffi(source: &str) -> String {
    let exports = exports(Side::C);
    let codes = codes(source, "HC_");
    let mut out = String::new();
    let _ = writeln!(out, "### Entry points\n");
    let _ = writeln!(
        out,
        "{} functions. Each is `extern \"C\"`, takes nothing it has to free and \
         returns an `HcStatus`. The feature column is the Cargo feature the \
         library has to be built with for the entry point to exist.\n",
        exports.len()
    );
    out.push_str("| Prototype | Feature | What it does |\n| --- | --- | --- |\n");
    for export in &exports {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            prototype(export),
            feature_cell(export),
            export.summary()
        );
    }
    let _ = writeln!(out, "\n### Status codes\n");
    let _ = writeln!(
        out,
        "`HcStatus` is `int`. Zero is success and every failure is negative. \
         The values are stable.\n"
    );
    out.push_str("| Code | Value | Meaning |\n| --- | --- | --- |\n");
    for code in &codes {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            code.name, code.value, code.summary
        );
    }
    out
}

fn render_wasm(source: &str) -> String {
    let exports = exports(Side::Wasm);
    let codes = codes(source, "HC_ERR");
    let mut out = String::new();
    let _ = writeln!(out, "### Exports\n");
    let _ = writeln!(
        out,
        "{} functions. Types are the WebAssembly ones: `i64` crosses into \
         JavaScript as a `BigInt`, everything else as a `number`, and a pointer \
         is a byte offset into `memory`. The feature column is the Cargo \
         feature the module has to be built with for the export to exist.\n",
        exports.len()
    );
    out.push_str("| Export | Feature | What it does |\n| --- | --- | --- |\n");
    for export in &exports {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            wasm_signature(export),
            feature_cell(export),
            export.summary()
        );
    }
    let _ = writeln!(out, "\n### Error sentinels\n");
    let _ = writeln!(
        out,
        "A function that returns `i64` returns one of these instead of trapping. \
         All are at or below `HC_ERR_FLOOR`, and no legitimate result is: the \
         ranges above say what each export answers for.\n"
    );
    out.push_str("| Sentinel | Value | Meaning |\n| --- | --- | --- |\n");
    for code in &codes {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            code.name, code.value, code.summary
        );
    }
    out
}

/// The README with the generated section replaced.
fn splice(readme: &str, generated: &str) -> String {
    let start = readme
        .find(START)
        .unwrap_or_else(|| panic!("README lacks the start marker {START}"))
        + START.len();
    let end = readme
        .find(END)
        .unwrap_or_else(|| panic!("README lacks the end marker {END}"));
    assert!(start <= end, "the markers are in the wrong order");
    format!(
        "{}\n\n{}\n{}",
        &readme[..start],
        generated.trim_end(),
        &readme[end..]
    )
}

fn check(readme_path: &str, generated: &str) {
    let committed = read(readme_path);
    let rendered = splice(&committed, generated);
    if rendered == committed {
        return;
    }
    if std::env::var_os("UPDATE_ABI").is_some() {
        if let Err(error) = std::fs::write(readme_path, &rendered) {
            panic!("could not write {readme_path}: {error}")
        }
        return;
    }
    let first_difference = rendered
        .lines()
        .zip(committed.lines())
        .position(|(left, right)| left != right)
        .map_or(0, |index| index + 1);
    panic!(
        "{readme_path} has drifted from the source (first difference at line \
         {first_difference}); run `UPDATE_ABI=1 cargo test -p hyper-calendar --test abi` \
         and read the diff"
    );
}

#[test]
fn the_c_abi_readme_lists_every_export() {
    check(FFI_README, &render_ffi(&read(FFI_SOURCE)));
}

#[test]
fn the_wasm_readme_lists_every_export() {
    check(WASM_README, &render_wasm(&read(WASM_SOURCE)));
}

/// The heading of the twin table in the WebAssembly README.
const TWINS: &str = "### Twins";

/// The rows of the twin table: the WebAssembly names, the C names and the
/// reason, each name cell `—` or a list of names in backticks. The first
/// cell says what the row is about and is not read.
fn twin_rows(readme: &str) -> Vec<(Vec<String>, Vec<String>, String)> {
    let at = readme
        .find(&format!("\n{TWINS}\n"))
        .unwrap_or_else(|| panic!("the README has no heading {TWINS}"));
    let names = |cell: &str| -> Vec<String> {
        if cell == "—" {
            return Vec::new();
        }
        cell.split(", ")
            .map(|name| {
                assert!(
                    name.starts_with('`') && name.ends_with('`'),
                    "a twin cell lists names in backticks: {cell}"
                );
                name.trim_matches('`').to_owned()
            })
            .collect()
    };
    let mut rows = Vec::new();
    for line in readme[at..]
        .lines()
        .skip_while(|line| !line.starts_with("| "))
        .skip(2)
    {
        if !line.starts_with('|') {
            break;
        }
        let cells: Vec<&str> = line.trim_matches('|').split(" | ").map(str::trim).collect();
        assert_eq!(cells.len(), 4, "a twin row has four cells: {line}");
        rows.push((names(cells[1]), names(cells[2]), cells[3].to_owned()));
    }
    assert!(!rows.is_empty(), "no twin table after {TWINS}");
    rows
}

/// The unpaired names of each surface, and whether every one of them is in
/// exactly one row of the twin table with a reason, and every name the
/// table lists is unpaired on its own surface.
fn twin_table_problems(
    wasm: &BTreeSet<String>,
    ffi: &BTreeSet<String>,
    rows: &[(Vec<String>, Vec<String>, String)],
) -> Vec<String> {
    let mut problems = Vec::new();
    for (side, own, other, column) in [("WebAssembly", wasm, ffi, 0), ("C", ffi, wasm, 1)] {
        for name in own.difference(other) {
            let count = rows
                .iter()
                .filter(|row| if column == 0 { &row.0 } else { &row.1 }.contains(name))
                .count();
            if count != 1 {
                problems.push(format!(
                    "the {side} export `{name}` has no twin of the same name and is in {count} rows of the twin table, not one"
                ));
            }
        }
        for row in rows {
            for name in if column == 0 { &row.0 } else { &row.1 } {
                if !own.contains(name) {
                    problems.push(format!(
                        "the twin table lists `{name}`, which the {side} surface does not export"
                    ));
                } else if other.contains(name) {
                    problems.push(format!(
                        "the twin table lists `{name}`, which both surfaces export"
                    ));
                }
            }
        }
    }
    for (wasm_names, ffi_names, reason) in rows {
        if reason.is_empty() || (wasm_names.is_empty() && ffi_names.is_empty()) {
            problems.push(format!(
                "a twin row with no names or no reason: {wasm_names:?} {ffi_names:?}"
            ));
        }
    }
    problems
}

fn names_of(side: Side) -> BTreeSet<String> {
    exports(side)
        .into_iter()
        .map(|export| export.name)
        .collect()
}

#[test]
fn every_export_has_a_twin_or_a_reason() {
    // A caller moving between the two surfaces finds the same function
    // under the same name, or the twin table in the WebAssembly README
    // says what stands in for it and why.
    let problems = twin_table_problems(
        &names_of(Side::Wasm),
        &names_of(Side::C),
        &twin_rows(&read(WASM_README)),
    );
    assert!(problems.is_empty(), "{}", problems.join("\n"));
}

#[test]
fn the_twin_check_catches_a_missing_twin_and_a_stale_row() {
    let set = |names: &[&str]| names.iter().map(|name| (*name).to_owned()).collect();
    let row = |wasm: &[&str], ffi: &[&str]| {
        (
            wasm.iter().map(|name| (*name).to_owned()).collect(),
            ffi.iter().map(|name| (*name).to_owned()).collect(),
            "a reason".to_owned(),
        )
    };
    let wasm = set(&["hc_a", "hc_b", "hc_shared"]);
    let ffi = set(&["hc_c", "hc_shared"]);
    // Every unpaired name in a row: no problem.
    assert!(twin_table_problems(&wasm, &ffi, &[row(&["hc_a", "hc_b"], &["hc_c"])]).is_empty());
    // `hc_b` left out of the table: caught.
    let missing = twin_table_problems(&wasm, &ffi, &[row(&["hc_a"], &["hc_c"])]);
    assert!(
        missing.iter().any(|problem| problem.contains("`hc_b`")),
        "{missing:?}"
    );
    // A row naming an export that both surfaces have, or one that is gone.
    let stale = twin_table_problems(
        &wasm,
        &ffi,
        &[row(&["hc_a", "hc_b", "hc_shared", "hc_gone"], &["hc_c"])],
    );
    assert!(
        stale.iter().any(|problem| problem.contains("`hc_shared`")),
        "{stale:?}"
    );
    assert!(
        stale.iter().any(|problem| problem.contains("`hc_gone`")),
        "{stale:?}"
    );
    // A row with no reason.
    let mut bare = row(&["hc_a", "hc_b"], &["hc_c"]);
    bare.2.clear();
    assert!(!twin_table_problems(&wasm, &ffi, &[bare]).is_empty());
}

/// The text of every Rust file of a boundary crate's tests: `src/tests.rs`
/// and the files under `src/tests/`.
fn boundary_tests(crate_dir: &str) -> String {
    let mut text = read(&format!("{crate_dir}/src/tests.rs"));
    let mut files: Vec<_> = std::fs::read_dir(format!("{crate_dir}/src/tests"))
        .unwrap_or_else(|error| panic!("could not read {crate_dir}/src/tests: {error}"))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "rs"))
        .collect();
    files.sort();
    for path in files {
        text.push_str(&read(&path.to_string_lossy()));
    }
    text
}

/// Whether `name` occurs in `text` as a whole identifier.
fn names_identifier(text: &str, name: &str) -> bool {
    let word = |byte: u8| byte.is_ascii_alphanumeric() || byte == b'_';
    let bytes = text.as_bytes();
    text.match_indices(name).any(|(at, _)| {
        let before = at == 0 || !word(bytes[at - 1]);
        let after = bytes.get(at + name.len()).is_none_or(|byte| !word(*byte));
        before && after
    })
}

/// The exports no test of the boundary crate names.
fn unnamed_exports(side: Side, crate_dir: &str) -> Vec<String> {
    let tests = boundary_tests(crate_dir);
    exports(side)
        .into_iter()
        .filter(|export| !names_identifier(&tests, &export.name))
        .map(|export| export.name)
        .collect()
}

#[test]
fn every_export_is_named_by_a_test_of_its_boundary() {
    // An export that no Rust test of its own crate calls is one whose
    // marshalling nothing checks: a swapped argument, a sentinel that does
    // not come back as the status the README lists. The shared line-makers
    // have their own tests in the facade; this is the glue.
    for (side, crate_dir) in [(Side::Wasm, WASM_CRATE), (Side::C, FFI_CRATE)] {
        let unnamed = unnamed_exports(side, crate_dir);
        assert!(
            unnamed.is_empty(),
            "exports of {crate_dir} no test names: {unnamed:?}"
        );
    }
}

#[test]
fn the_identifier_check_matches_whole_names_only() {
    assert!(names_identifier("hc_a(1)", "hc_a"));
    assert!(names_identifier("x = hc_a;", "hc_a"));
    assert!(!names_identifier("hc_a_b(1)", "hc_a"));
    assert!(!names_identifier("my_hc_a(1)", "hc_a"));
    assert!(names_identifier("hc_a_b(1) hc_a", "hc_a"));
}

/// The rows of the ranges table after `heading`: the names in each row's
/// second cell, and its third cell.
fn ranges(readme: &str, heading: &str) -> Vec<(Vec<String>, String)> {
    let at = readme
        .find(&format!("\n{heading}\n"))
        .unwrap_or_else(|| panic!("the README has no heading {heading}"));
    let mut rows = Vec::new();
    for line in readme[at..]
        .lines()
        .skip_while(|line| !line.starts_with("| "))
        .skip(2)
    {
        if !line.starts_with('|') {
            break;
        }
        let cells: Vec<&str> = line.trim_matches('|').split(" | ").map(str::trim).collect();
        assert_eq!(cells.len(), 3, "a range row has three cells: {line}");
        let names = cells[1]
            .split(", ")
            .map(|name| name.trim_matches('`').to_owned())
            .collect();
        rows.push((names, cells[2].to_owned()));
    }
    assert!(!rows.is_empty(), "no ranges table after {heading}");
    rows
}

/// The `i64` inputs of an export: its parameters of type `i64` exactly,
/// so that a `u64` or a pointer to an `i64` is not one.
fn i64_inputs(export: &Export) -> Vec<&str> {
    export
        .params
        .iter()
        .filter(|(_, ty)| ty == "i64")
        .map(|(name, _)| name.as_str())
        .collect()
}

/// What is wrong with the ranges table against the exports `needs_a_row`
/// picks: each such export has exactly one row, and the row names each of
/// its `i64` inputs in backticks, so that it says what range of that input
/// it answers for; and every name in the table is such an export.
fn range_problems(
    exports: &[Export],
    ranges: &[(Vec<String>, String)],
    needs_a_row: impl Fn(&Export) -> bool,
) -> Vec<String> {
    let mut problems = Vec::new();
    let needed: Vec<&Export> = exports
        .iter()
        .filter(|export| needs_a_row(export))
        .collect();
    for export in &needed {
        let rows: Vec<&String> = ranges
            .iter()
            .filter(|(names, _)| names.contains(&export.name))
            .map(|(_, range)| range)
            .collect();
        if rows.len() != 1 {
            problems.push(format!(
                "`{}` has {} rows, not one",
                export.name,
                rows.len()
            ));
            continue;
        }
        if rows[0].is_empty() {
            problems.push(format!(
                "`{}` does not say what it answers for",
                export.name
            ));
        }
        for input in i64_inputs(export) {
            if !rows[0].contains(&format!("`{input}`")) {
                problems.push(format!(
                    "the row of `{}` does not name its input `{input}`",
                    export.name
                ));
            }
        }
    }
    for (names, _) in ranges {
        for name in names {
            if !needed.iter().any(|export| &export.name == name) {
                problems.push(format!("`{name}` has a row but needs none"));
            }
        }
    }
    problems
}

fn check_ranges(
    side: Side,
    readme_path: &str,
    heading: &str,
    needs_a_row: impl Fn(&Export) -> bool,
) {
    let exports = exports(side);
    let problems = range_problems(&exports, &ranges(&read(readme_path), heading), needs_a_row);
    assert!(
        problems.is_empty(),
        "{readme_path}, {heading}:\n{}",
        problems.join("\n")
    );
}

/// A WebAssembly export needs a row when it returns an `i64`, which is
/// every export but `hc_alloc` and `hc_free`.
fn wasm_needs_a_row(export: &Export) -> bool {
    export.returns.as_deref() == Some("i64")
}

/// A C entry point needs a row when it takes an `int64_t` or writes one.
/// The types are the parsed ones, so a `uint64_t` is neither.
fn ffi_needs_a_row(export: &Export) -> bool {
    !i64_inputs(export).is_empty() || export.params.iter().any(|(_, ty)| ty == "*mut i64")
}

#[test]
fn every_i64_export_of_the_wasm_module_documents_its_range() {
    // Each must say what it answers for, so that a caller knows which
    // numbers are results and which are refusals, and what range of each
    // `i64` it takes.
    check_ranges(Side::Wasm, WASM_README, "### Ranges", wasm_needs_a_row);
}

#[test]
fn every_int64_entry_point_of_the_c_abi_documents_its_range() {
    check_ranges(Side::C, FFI_README, "## Errors and ranges", ffi_needs_a_row);
}

#[test]
fn the_range_check_catches_a_missing_row_and_an_unnamed_input() {
    let export = |name: &str, params: &[(&str, &str)], returns: Option<&str>| Export {
        name: name.to_owned(),
        params: params
            .iter()
            .map(|(name, ty)| ((*name).to_owned(), (*ty).to_owned()))
            .collect(),
        returns: returns.map(str::to_owned),
        docs: vec!["s".to_owned()],
        feature: "always".to_owned(),
        is_unsafe: false,
    };
    let exports = [
        export("hc_day", &[("fixed", "i64")], Some("i64")),
        export(
            "hc_week",
            &[("seconds", "u64"), ("out_week", "*mut u64")],
            Some("HcStatus"),
        ),
        export("hc_free", &[("pointer", "*mut u8")], None),
    ];
    let row = |names: &[&str], range: &str| {
        (
            names
                .iter()
                .map(|name| (*name).to_owned())
                .collect::<Vec<_>>(),
            range.to_owned(),
        )
    };
    let good = [row(&["hc_day"], "`fixed` from 1")];
    assert!(range_problems(&exports, &good, wasm_needs_a_row).is_empty());
    // No row at all, and a row that does not name the input.
    assert!(!range_problems(&exports, &[row(&["hc_other"], "x")], wasm_needs_a_row).is_empty());
    let unnamed = range_problems(&exports, &[row(&["hc_day"], "every day")], wasm_needs_a_row);
    assert!(
        unnamed.iter().any(|problem| problem.contains("`fixed`")),
        "{unnamed:?}"
    );
    // Two rows for one export, and a row for an export that needs none.
    let twice = [row(&["hc_day"], "`fixed`"), row(&["hc_day"], "`fixed`")];
    assert!(!range_problems(&exports, &twice, wasm_needs_a_row).is_empty());
    let extra = [row(&["hc_day"], "`fixed`"), row(&["hc_free"], "x")];
    assert!(!range_problems(&exports, &extra, wasm_needs_a_row).is_empty());
    // A `uint64_t` input or out-parameter is not an `int64_t` one.
    assert!(!ffi_needs_a_row(&exports[1]));
    assert!(ffi_needs_a_row(&exports[0]));
}
