//! Renders the export tables in the two boundary crates' READMEs and fails
//! when the committed tables have drifted from the source.
//!
//! The C ABI and the WebAssembly surface are the two places a caller who
//! cannot be assumed to read Rust meets this library, so their READMEs have
//! to list every export with its signature. A hand-written list is the kind
//! of document that is right on the day it is written. These are rendered
//! from `src/lib.rs` of each crate, spliced between two markers in the
//! README, and compared, so an entry point without a row — or a row without
//! an entry point — fails the build. The prose around the markers is
//! written; only the tables are generated.
//!
//! To accept a change: `UPDATE_ABI=1 cargo test -p hyper-calendar --test
//! abi`, then read the diff before committing it.

use std::fmt::Write as _;

const FFI_SOURCE: &str = "../hyper-calendar-ffi/src/lib.rs";
const FFI_README: &str = "../hyper-calendar-ffi/README.md";
const WASM_SOURCE: &str = "../hyper-calendar-wasm/src/lib.rs";
const WASM_README: &str = "../hyper-calendar-wasm/README.md";

const START: &str = "<!-- generated by crates/hyper-calendar/tests/abi.rs: start -->";
const END: &str = "<!-- generated by crates/hyper-calendar/tests/abi.rs: end -->";

/// One exported function, as read from the source.
struct Export {
    name: String,
    /// Parameter names and their Rust types, in order.
    params: Vec<(String, String)>,
    /// The Rust return type, if any.
    returns: Option<String>,
    /// The first paragraph of the doc comment.
    summary: String,
}

/// One `pub const` status code or sentinel.
struct Code {
    name: String,
    value: String,
    summary: String,
}

fn read(path: &str) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|error| panic!("could not read {path}: {error}"))
}

/// The doc lines immediately above `index`, oldest first.
fn docs_above<'a>(lines: &[&'a str], index: usize) -> Vec<&'a str> {
    let mut docs = Vec::new();
    let mut cursor = index;
    while cursor > 0 && lines[cursor - 1].trim_start().starts_with("///") {
        cursor -= 1;
        docs.push(lines[cursor].trim_start().trim_start_matches("///").trim());
    }
    docs.reverse();
    docs
}

/// The first paragraph of a doc comment, as one line.
fn summary_of(docs: &[&str]) -> String {
    // Intra-doc links are Markdown for rustdoc, not for a README.
    docs.iter()
        .take_while(|line| !line.is_empty())
        .copied()
        .collect::<Vec<_>>()
        .join(" ")
        .replace("[`", "`")
        .replace("`]", "`")
}

/// Every `#[unsafe(no_mangle)]` function in the source, in order.
fn exports(source: &str) -> Vec<Export> {
    let lines: Vec<&str> = source.lines().collect();
    let mut out = Vec::new();
    for (index, line) in lines.iter().enumerate() {
        if line.trim() != "#[unsafe(no_mangle)]" {
            continue;
        }
        let summary = summary_of(&docs_above(&lines, index));
        assert!(
            !summary.is_empty(),
            "the export after line {} has no doc summary",
            index + 1
        );
        // The signature runs from the next line to the line that opens the
        // body; rustfmt may spread it over several.
        let mut signature = String::new();
        let mut cursor = index + 1;
        loop {
            let piece = lines[cursor].trim();
            signature.push_str(piece);
            signature.push(' ');
            if piece.ends_with('{') {
                break;
            }
            cursor += 1;
        }
        out.push(parse_signature(&signature, summary));
    }
    assert!(!out.is_empty(), "no exports found");
    out
}

/// `pub [unsafe] extern "C" fn NAME(PARAMS) [-> RET] {` into its parts.
fn parse_signature(signature: &str, summary: String) -> Export {
    let after_fn = signature
        .split(" fn ")
        .nth(1)
        .unwrap_or_else(|| panic!("not a function signature: {signature}"));
    let (Some(open), Some(close)) = (after_fn.find('('), after_fn.rfind(')')) else {
        panic!("no parameter list in signature: {signature}")
    };
    let name = after_fn[..open].to_owned();
    let params = after_fn[open + 1..close]
        .split(',')
        .map(str::trim)
        .filter(|param| !param.is_empty())
        .map(|param| {
            let (name, ty) = param
                .split_once(':')
                .unwrap_or_else(|| panic!("{name}: parameter without a type: {param}"));
            (name.trim().to_owned(), ty.trim().to_owned())
        })
        .collect();
    let tail = after_fn[close + 1..].trim().trim_end_matches('{').trim();
    let returns = tail.strip_prefix("->").map(|ret| ret.trim().to_owned());
    Export {
        name,
        params,
        returns,
        summary,
    }
}

/// Every `pub const` whose name starts with `prefix`, with its doc summary.
fn codes(source: &str, prefix: &str) -> Vec<Code> {
    let lines: Vec<&str> = source.lines().collect();
    let mut out = Vec::new();
    for (index, line) in lines.iter().enumerate() {
        let Some(rest) = line.strip_prefix("pub const ") else {
            continue;
        };
        if !rest.starts_with(prefix) {
            continue;
        }
        let Some((name, rest)) = rest.split_once(':') else {
            panic!("constant without a type on line {}", index + 1)
        };
        let Some((_, value)) = rest.split_once('=') else {
            panic!("constant without a value on line {}", index + 1)
        };
        out.push(Code {
            name: name.trim().to_owned(),
            value: value.trim().trim_end_matches(';').trim().to_owned(),
            summary: summary_of(&docs_above(&lines, index)),
        });
    }
    assert!(!out.is_empty(), "no constants with prefix {prefix}");
    out
}

/// The C spelling of a Rust type used at the boundary.
///
/// Unknown types are a panic on purpose: a new type at the boundary needs a
/// C name decided by a person, not guessed by a table.
fn c_type(rust: &str) -> String {
    match rust {
        "i64" => "int64_t".to_owned(),
        "u64" => "uint64_t".to_owned(),
        "i32" => "int32_t".to_owned(),
        "u32" => "uint32_t".to_owned(),
        "u8" => "uint8_t".to_owned(),
        "usize" => "size_t".to_owned(),
        "c_int" => "int".to_owned(),
        "c_char" => "char".to_owned(),
        "HcStatus" => "HcStatus".to_owned(),
        _ => {
            if let Some(inner) = rust.strip_prefix("*mut ") {
                format!("{} *", c_type(inner))
            } else if let Some(inner) = rust.strip_prefix("*const ") {
                format!("const {} *", c_type(inner))
            } else {
                panic!("no C spelling for `{rust}`; add one to c_type")
            }
        }
    }
}

/// A C prototype for an export.
fn prototype(export: &Export) -> String {
    let params: Vec<String> = export
        .params
        .iter()
        .map(|(name, ty)| {
            let ty = c_type(ty);
            if ty.ends_with('*') {
                format!("{ty}{name}")
            } else {
                format!("{ty} {name}")
            }
        })
        .collect();
    let returns = export.returns.as_deref().map_or("void".to_owned(), c_type);
    format!("{returns} {}({});", export.name, params.join(", "))
}

/// A Rust-typed signature for a WebAssembly export.
fn wasm_signature(export: &Export) -> String {
    let params: Vec<String> = export
        .params
        .iter()
        .map(|(name, ty)| format!("{name}: {ty}"))
        .collect();
    match &export.returns {
        Some(ret) => format!("{}({}) -> {ret}", export.name, params.join(", ")),
        None => format!("{}({})", export.name, params.join(", ")),
    }
}

fn render_ffi(source: &str) -> String {
    let exports = exports(source);
    let codes = codes(source, "HC_");
    let mut out = String::new();
    let _ = writeln!(out, "### Entry points\n");
    let _ = writeln!(
        out,
        "{} functions. Each is `extern \"C\"`, takes nothing it has to free and \
         returns an `HcStatus`.\n",
        exports.len()
    );
    out.push_str("| Prototype | What it does |\n| --- | --- |\n");
    for export in &exports {
        let _ = writeln!(out, "| `{}` | {} |", prototype(export), export.summary);
    }
    let _ = writeln!(out, "\n### Status codes\n");
    let _ = writeln!(
        out,
        "`HcStatus` is `int`. Zero is success and every failure is negative. \
         The values are stable.\n"
    );
    out.push_str("| Code | Value | Meaning |\n| --- | --- | --- |\n");
    for code in &codes {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            code.name, code.value, code.summary
        );
    }
    out
}

fn render_wasm(source: &str) -> String {
    let exports = exports(source);
    let codes = codes(source, "HC_ERR");
    let mut out = String::new();
    let _ = writeln!(out, "### Exports\n");
    let _ = writeln!(
        out,
        "{} functions. Types are the WebAssembly ones: `i64` crosses into \
         JavaScript as a `BigInt`, everything else as a `number`, and a pointer \
         is a byte offset into `memory`.\n",
        exports.len()
    );
    out.push_str("| Export | What it does |\n| --- | --- |\n");
    for export in &exports {
        let _ = writeln!(out, "| `{}` | {} |", wasm_signature(export), export.summary);
    }
    let _ = writeln!(out, "\n### Error sentinels\n");
    let _ = writeln!(
        out,
        "A function that returns `i64` returns one of these instead of trapping. \
         All are at or below `HC_ERR_FLOOR`, which no day number reaches.\n"
    );
    out.push_str("| Sentinel | Value | Meaning |\n| --- | --- | --- |\n");
    for code in &codes {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            code.name, code.value, code.summary
        );
    }
    out
}

/// The README with the generated section replaced.
fn splice(readme: &str, generated: &str) -> String {
    let start = readme
        .find(START)
        .unwrap_or_else(|| panic!("README lacks the start marker {START}"))
        + START.len();
    let end = readme
        .find(END)
        .unwrap_or_else(|| panic!("README lacks the end marker {END}"));
    assert!(start <= end, "the markers are in the wrong order");
    format!(
        "{}\n\n{}\n{}",
        &readme[..start],
        generated.trim_end(),
        &readme[end..]
    )
}

fn check(readme_path: &str, generated: &str) {
    let committed = read(readme_path);
    let rendered = splice(&committed, generated);
    if rendered == committed {
        return;
    }
    if std::env::var_os("UPDATE_ABI").is_some() {
        if let Err(error) = std::fs::write(readme_path, &rendered) {
            panic!("could not write {readme_path}: {error}")
        }
        return;
    }
    let first_difference = rendered
        .lines()
        .zip(committed.lines())
        .position(|(left, right)| left != right)
        .map_or(0, |index| index + 1);
    panic!(
        "{readme_path} has drifted from the source (first difference at line \
         {first_difference}); run `UPDATE_ABI=1 cargo test -p hyper-calendar --test abi` \
         and read the diff"
    );
}

#[test]
fn the_c_abi_readme_lists_every_export() {
    check(FFI_README, &render_ffi(&read(FFI_SOURCE)));
}

#[test]
fn the_wasm_readme_lists_every_export() {
    check(WASM_README, &render_wasm(&read(WASM_SOURCE)));
}

#[test]
fn the_two_surfaces_share_their_vocabulary() {
    // A name that exists in both crates should mean the same thing, so a
    // caller moving from one to the other is not surprised. The two are not
    // required to export the same set — the C ABI uses out-parameters and
    // the WebAssembly surface uses sentinels — but a shared name with a
    // different summary is a documentation bug.
    let ffi = exports(&read(FFI_SOURCE));
    let wasm = exports(&read(WASM_SOURCE));
    for export in &ffi {
        if let Some(twin) = wasm.iter().find(|candidate| candidate.name == export.name) {
            assert!(
                !twin.summary.is_empty() && !export.summary.is_empty(),
                "{} is exported by both and documented by neither",
                export.name
            );
        }
    }
}
